### ISSUE TITLE
i've sent 262 ether to kraken but the balance is not updating

### ISSUE THREAD

**Issue by lechatnieger** [ethereum/meteor-dapp-wallet#101]
it is only showing 0.31 ether as a transaction

https://www.etherchain.org/account/0xcf9b6058259b6f5d920ece377d6e052238f60827#txreceived

http://etherscan.io/address/0xcf9b6058259b6f5d920ece377d6e052238f60827

have i lost my funds?

**Comment by alexvandesande** [comment]
No. Your funds are there, see 'balance'. It's a known issue with detecting funds sent from contracts on both the kraken and the blockchain explorers implementations. Contact kraken tech support.
