### ISSUE TITLE
"Watch contract" doesn't add contracts

### ISSUE THREAD

**Issue by SteffenIvanhoe** [ethereum/meteor-dapp-wallet#102]
I created a multi-sig wallet contract. Did it on one machine with 2 signatures necessary to go over the daily limit. Then I transmitted the contract address and the JSON interface description to a second machine (the second signer) to be abele to sign the contract there. Tried to set it up in the Wallet with the "Watch contract" function. I fill in the name, address and JSON and press OK. Nothing happens, no error message, no ok message and no new contract is displayed. This way the construction of a multi-sig wallet is not possible. 

I have watched this "fail silent" behaviour multiple times while playing with the wallet. I believe that this has to be changed for opening the wallet to a broader audience!

**Comment by frozeman** [comment]
You actually simply copy the contract address and go to "Add Wallet" -> import wallet and add the address there.

Though there might be a bug with adding watched contracts @alexvandesande can you have a look?

**Comment by SteffenIvanhoe** [comment]
Import worked, thank you!

I found that this multi-sig behaviour is not really what I looked for because both owners have the same rights and both can independently initiate transactions up to the daily limit. What I'm looking for is a 2-factor authentication method where there is one owner and one signer (who can not send money on its own). This way I own the wallet and can use it for small payments but still have only a limit risk with respect to attacks on my machine. For the more seldom bigger transactions I ask my wife to co-sign the transaction. But whatever is running on her machine should not be able to initiate transactions on its own.

2-factor authentication is badly needed with growing worth of the Ethers ;-).

**Comment by frozeman** [comment]
Even if she can invoke tx too, you can simply ignore or disprove it.
What youre asking is basically the same with a small change. You're encrouaged to build your own contract ;)

**Comment by SteffenIvanhoe** [comment]
But up to the daily limit I can not disprove the tx. If a virus on her machine steals the private key then it can setup a daily transfer up to the contracts limit. I would be forced to watch my wallet closely to find out in time. From a security point of view this is more than a small change. (My own machine has a much tighter security then the one of my wife.)

But you are right that I could try to deploy my own contract to do that. Which then requires that the bug that I found in the "Watch contract" functionality (see above) must be removed!

**Comment by frozeman** [comment]
Set the daily limit when you create the contract to 0

**Comment by SteffenIvanhoe** [comment]
Might be an idea. Thanks and bye!

**Comment by alexvandesande** [comment]
Sorry about the watch contract bug, it's my fault. I've added a "new feature" in the latest version but didn't test it properly and it broke that functionality. It has been fixed on develop and will be working again on the next release. If you open the previous version and add the contract there, then the watched contract will persists on the newest version.

**Comment by frozeman** [comment]
(Not for linux divs though, as electron change the app path for them..)
