### ISSUE TITLE
Finding peers / network connection very unreliable

### ISSUE THREAD

**Issue by SteffenIvanhoe** [ethereum/meteor-dapp-wallet#103]
I find it quite difficult to connect the wallet to the blockchain. It often hangs in the "Looking for peers" mode with no resolution. Multiple aborts and restarts are necessary to finally find some peers and get the blockchain updated. The update itself is rather slow. Finally when everything is up the wallet loses connection to peers after some time and never regains it without a restart.

I use Windows 7 64-bit and have a reliable high speed web access. I do not see similar problems with updating e.g. my Bitcoin or Dash full nodes.

The problem is that I can not distinguish whether the wallet is indeed waiting for something (as it pretends to do) or is already dead and will never come back.

**Comment by frozeman** [comment]
@bas-vk @fjl any idea why connections are slow on windows? I read this already multiple times that windows downloads blocks slowly etc..

@bas-vk maybe something with the named pipes? I personally think its in the network layer.

@SteffenIvanhoe i close this here, as this is an issue, which needs to be addressed in github.com/ethereum/go-ethereum
