### ISSUE TITLE
Update the suggestion to connect the wallet?

### ISSUE THREAD

**Issue by alexvandesande** [ethereum/meteor-dapp-wallet#105]
This is the current error when the wallet can't connect to the node:

```
Unable to connect. Please start geth with the following options:

geth --rpc --rpccorsdomain "http://localhost:3050"
```

I believe that's outdated no? Shouldn't the correct command be `--ipcpath ~/Library/Ethereum/geth.ipc` ?

**Comment by frozeman** [comment]
In mist it shows another message with an pic path

**Comment by frozeman** [comment]
https://github.com/ethereum/meteor-dapp-wallet/blob/master/app/i18n/wallet.en.i18n.json#L23-L24
