### ISSUE TITLE
Not possible to delete contract (V0.5.2, working with TestNet)

### ISSUE THREAD

**Issue by SteffenIvanhoe** [ethereum/meteor-dapp-wallet#117]
Trying to delete a contract shows no response and the contract does not disappear.

**Comment by luclu** [comment]
@SteffenIvanhoe could you kindly try to delete the contract with the latest version [0.7.2](https://github.com/ethereum/mist/releases)?

**Comment by luclu** [comment]
duplicate of https://github.com/ethereum/meteor-dapp-wallet/issues/177
