### ISSUE TITLE
Contract creation: parameters don't work!?

### ISSUE THREAD

**Issue by SteffenIvanhoe** [ethereum/meteor-dapp-wallet#118]
To become familiar with the contract publishing in the wallet I tried to load the default wallet.sol contract. It seems to work but although I gave two owners ![screen shot](https://cloud.githubusercontent.com/assets/5699994/13730568/22b84944-e953-11e5-8491-a45e114a1c20.JPG) the contract shows after creation 
![owners](https://cloud.githubusercontent.com/assets/5699994/13730614/083d3cfe-e954-11e5-947e-ee7a7f921ef3.JPG)
No error message was given. Did I make a syntax error in specifying the address array in the `owners`field or is there a bug in the code?

**Comment by frozeman** [comment]
You should use quotes i guess: `["0x1344...", "0x234656..."]`

**Comment by SteffenIvanhoe** [comment]
Yes, this works! Now I see 3 owners although I have only given 2. But that seems to be a "problem" of the wallet code. It automatically adds the wallet creater as owner. It might make sense to check that this owner is not again delivered a second time as owner parameter. At least that would make such a widely used contract a bit more memory and computation efficient, or?
