### ISSUE TITLE
Your computers time is out of sync!  ??

### ISSUE THREAD

**Issue by lubah** [ethereum/meteor-dapp-wallet#119]
![image](https://cloud.githubusercontent.com/assets/4357945/13730672/a7057488-e92b-11e5-9381-1997c03006ad.png)

really?  <20 seconds off?  cmon...

**Comment by frozeman** [comment]
The block time of Ethereum is 16s, so if your'e 20s off your chain might have problems syncing..

**Comment by greggdourgarian** [comment]
getting this issue as well and my computer's time is automatically managed

**Comment by vindard** [comment]
I've been getting the same issue. My computer time is also managed automatically and I had to manually edit away the 13s difference for it to eventually work.

**Comment by ohmslawct** [comment]
I changed the time server to NIST instead of Microsoft, then updated and it worked.

**Comment by frozeman** [comment]
This should be fixed in the lates 0.6.2
