### ISSUE TITLE
missing wallet icon

### ISSUE THREAD

**Issue by debris** [ethereum/meteor-dapp-wallet#12]
after creating new wallet go to 'send money' tab. Wallet icon is missing there (pic. 1). After pressing it, and selecting other wallet, the icon appears (pic. 2). if we select first wallet again, the icon is also ok (pic 3).

pic 1.
![screen shot 2015-06-09 at 12 37 47](https://cloud.githubusercontent.com/assets/2613714/8056005/76eaaf32-0ea4-11e5-9269-d6503cb3e0e1.png)
pic 2.
![screen shot 2015-06-09 at 12 38 34](https://cloud.githubusercontent.com/assets/2613714/8056006/78627a66-0ea4-11e5-9a38-8785e2cca1c9.png)
pic 3.
![screen shot 2015-06-09 at 12 38 51](https://cloud.githubusercontent.com/assets/2613714/8056011/829f1994-0ea4-11e5-9f2c-d66d4a34e8c8.png)

**Comment by frozeman** [comment]
Thats a bug and is fixed.
