### ISSUE TITLE
Node crash

### ISSUE THREAD

**Issue by willg6921** [ethereum/meteor-dapp-wallet#123]
how do I fix the below ?

![image](https://cloud.githubusercontent.com/assets/17826126/13741999/1c82ede0-ea25-11e5-91ff-bfd24fdbf07f.png)

Thanks

**Comment by alexvandesande** [comment]
Thanks for reporting. To reduce duplication of issues I will be merging all these threads into a single issue: https://github.com/ethereum/mist/issues/243
