### ISSUE TITLE
Transfered 9 Btc to Ether wallet and only one appeared 

### ISSUE THREAD

**Issue by gregstee** [ethereum/meteor-dapp-wallet#126]
I have searched and searched but I cannot figure this out. 
0.3145 Bicoins were moved to my Ethereum wallet (9 Ether worth) but only 1 Ether arrived. I later moved 0.0344 to my wallet (1 Ether worth) and 1 Ether arrived. I now have 2 Ether for the price of 10.... I cannot figure out where I've gone wrong. I certainly don't have my maths wrong either.

Please help!

**Comment by alexvandesande** [comment]
If you used the integrated shape shift import, you should contact their support at: http://shapeshift.io

They are usually very responsive
