### ISSUE TITLE
 help me please

### ISSUE THREAD

**Issue by Dreva** [ethereum/meteor-dapp-wallet#131]
open ethereum wallet .exe 0.5.1
![ether](https://cloud.githubusercontent.com/assets/17955292/13901536/f3ae88de-ee2f-11e5-95ac-c8c9f402e21b.png)
what to do?

**Comment by rfikki** [comment]
Please update to latest version of wallet

**Comment by Dreva** [comment]
Thanks, I updated the wallet, but the problem ether to remove the purse, but do not reach the stock market (((

**Comment by alexvandesande** [comment]
> Thanks, I updated the wallet, but the problem ether to remove the purse, but do not reach the stock market (((

Do you mean ether is sent from the wallet but never reaches an exchange? Please post more information otherwise we can't help you..

**Comment by Dreva** [comment]
All thanks to this poloniex.com some problems ether it never came

**Comment by alexvandesande** [comment]
So the problem was due to Poloniex? I'm closing it then, thanks for reporting!
