### ISSUE TITLE
Nodes do not sync, ETH balance did not update

### ISSUE THREAD

**Issue by foxyjanny** [ethereum/meteor-dapp-wallet#132]
I transferred 150 ETH to my Ethereum wallet from my BTC wallet via Shape Shift (default  exchange platform for this Ethereum wallet) few days ago. Bitcoins were debited from my Mycelium wallet but never showed up as ETH in my Ethereum wallet. I contacted ShapeShift support and they confirmed the ETH were transferred. When I try to open the Ethereum wallet, the syncing of the nodes begins, but stops at one point and does not move further (full day now). I never succeeded to reopen my wallet. This is first time this happened, I transferred ETH from my Mycelium BTC wallet 3 times before and it went smooth. I'd appreciate any help in this. Thank you.
![ethereum 1](https://cloud.githubusercontent.com/assets/17959144/13903104/25e70760-ee29-11e5-9886-8373a628c56c.jpg)

**Comment by alexvandesande** [comment]
It seems you are running an old, out of date version of the wallet. Please download the latest, homestead compatible version and try again: https://github.com/ethereum/mist/releases/latest

**Comment by foxyjanny** [comment]
Hi Alex. Thank you for your answer. I did download the newest version (052) now, but I do not find an option how to open access my old wallet from there. It automatically opens a new account. How do I access my old wallet with all the funds from my new wallet? Thank you

**Comment by alexvandesande** [comment]
Do you remember if you changed any default configuration on the old wallet? You normally don't need to do anything, it opens the old funds automatically

**Comment by foxyjanny** [comment]
did not change anything. I just started the old wallet again and skipped the sync and it finally opened with updated balance. I'd still love to know if there's a way to transfer my old wallet into the new version. I guess I'll have to transfer it using an exchange platform such as shape shift? thanks
