### ISSUE TITLE
Ether not showing up in my wallet

### ISSUE THREAD

**Issue by malarchuck** [ethereum/meteor-dapp-wallet#133]
I downloaded the Ether wallet from ethereum.org 2 days ago. And used the shapeshift feature within the wallet to transfer Bitcoin to Ether into my "Account 1". The transfer was completed successfully but the Ether are not showing up in my Ether wallet. No transactions are showing up in my wallet.
*note: it has been 2 days now and my wallet is still showing "block synchronisation started". do the Ether come into my wallet after the synchronization is completed?

**Comment by GlossPan** [comment]
I have exactly the same problem.

**Comment by malarchuck** [comment]
It took about 50 hours for my wallet to finally synchronize. Once the process of synchronization finished, the Ether appeared in my wallet. So, it appears the synchronization process must be completed before the Ether are in your wallet.

**Comment by GlossPan** [comment]
At the moment Ethereal-Wallet says "downloading block" is that part of the same sync your talking about? Seems to be happening faster than 50 hours.

**Comment by malarchuck** [comment]
Yes, I noticed 2 different messages about downloading blocks and synchronization. From what I experienced, once you have finished downloading blocks and the synchronization process, your Ether should arrive.

**Comment by GlossPan** [comment]
Chhers, it seems to have finished downloading blocks and is now saying "processing blocks, please wait..." so i may have 50 hours to go afterall.

**Comment by MrMontana** [comment]
Same problem here. Though now when I try to sync it wont complete. Just freezes.

**Comment by malarchuck** [comment]
There were many times when the wallet would freeze for me as well. I would try to restart and eventually it finished syncing. I suspect it will take up to several days to complete.

**Comment by MrMontana** [comment]
How long did yours take?

**Comment by malarchuck** [comment]
I don't recall the exact time but it remember it taking all weekend long.

**Comment by luclu** [comment]
How are you going?

**Comment by luclu** [comment]
Closed as of inactivity.
