### ISSUE TITLE
Erroneous "Password incorrect" on attempting presale wallet import

### ISSUE THREAD

**Issue by mode80** [ethereum/meteor-dapp-wallet#134]
Hi avsa. 

I've been absent from ethereum for a while. Seeing the shiny new wallet on the home page, I decided it was time to finally import my presale wallet. (I had not done this before.) I was fairly horrified when I got the "Password Incorrect" error. Repeatedly. After many careful attempts. 

I spent a few stressful hours trying to figure out what part I'd got wrong. I was beginning to accept they were lost forever. On a total Hail Mary, I installed geth and tried it again via the command line. Original password = success!

Normally I'd submit a bug report with a bit more helpful detail, but I can't think of anything unusual about my scenario. Hopefully by reporting it early I might save someone from a similar panic.

If this ends up being very hard to reproduce, I can use the troublesome wallet file and poke around in the source once I have some time.

**Comment by hiddentao** [comment]
Thanks for the report. This is a known issue (see ethereum/mist#182) and will be fixed in the next release.

**Comment by luclu** [comment]
@mode80 please have a look at [this](https://github.com/ethereum/mist/issues/808#issuecomment-233608004) summary. I will close this should be solved in recent versions.
