### ISSUE TITLE
is wallet.sol included with packaged wallet somewhere?

### ISSUE THREAD

**Issue by step21** [ethereum/meteor-dapp-wallet#135]
Just curious how the wallet code is distributed inside the wallet. I checked the wallet binaries directory and its users files, but didn't find it.

**Comment by luclu** [comment]
Under the current distribution model the code of `wallet.sol` is being packed by the **electron-packager** npm-module into the binary of **Ethereum-Wallet**. 
That said the current model is subject to change rather soon to improve its auditability.
