### ISSUE TITLE
Lost bitcoins while transfering to the Ethereum wallet

### ISSUE THREAD

**Issue by RogierKonings** [ethereum/meteor-dapp-wallet#137]
Dear, i have send bitcoins to my Ethereum Wallet. I selected to transfer the amount of about 0.69 bitcoins  in the program. From my online wallet i than proceeded to send the 0.69 bitcoins. I did however only receive 0.69 ether. I think what went wrong was that the amount that i selected in the program was the amount of ether i wanted to receive( i thought it was the amount of bitcoins). But than my question arises, where did the rest of my bitcoins went?

**Comment by 5chdn** [comment]
They are at shapeshift. Go to shapeshift.io click on contact or support and tell them about your issue and include both the bitcoin transaction ID and a refund address. They will send you the coins back within 24 hours. Usually
