### ISSUE TITLE
Deposit timeout leads to lost BTC (compromise or bug?)

### ISSUE THREAD

**Issue by pibara** [ethereum/meteor-dapp-wallet#138]
Not sure if this is a bug or if the Linux binary had been compromised.
When using the deposit function in the wallet, there is a timeout. Aparently if the BTC deposit is not completed in a few minutes (not that rare when doing BTC transactions), the wallet app keeps giving the same timeout error message and apparently the BTC are lost to the person making the deposit. No BTC refunded, no Eth deposited, nothing, gone. As the idea of having a few minute timeout on a BTC transaction seems like too clueless to possibly be a designed feature, my best guess would be that the Linux binary has been compromised and someone is making a load of this scam.  If it's a bug, it's a real serious one, and the deposit function should probably be disabled until it is fixed! Anyway, rather anoyed about loosing 3.6 Eth worth of BTC on this one. Truly hope you guys find out if this is a bug or compromise.

**Comment by alexvandesande** [comment]
Bitcoin deposits are not native, we are just using shapeshift web client. You should contact them to request a refund on your ether
