### ISSUE TITLE
suggestion: progress bar for creating wallet

### ISSUE THREAD

**Issue by debris** [ethereum/meteor-dapp-wallet#14]
after creating new wallet I see active indicator (pic 1), but I don't know for what does it mean. It would be nice to have there progress bar similar to the one after making transaction (pic 2) :)

pic 1
![screen shot 2015-06-09 at 12 42 49](https://cloud.githubusercontent.com/assets/2613714/8056111/4dacbf06-0ea5-11e5-9548-5d60b20ede8a.png)

pic 2
![screen shot 2015-06-09 at 12 42 56](https://cloud.githubusercontent.com/assets/2613714/8056112/50cf3f9c-0ea5-11e5-840b-3b634b55cf50.png)

**Comment by frozeman** [comment]
There is a progress bar, but the initial loading spinner is only shown until i received the contract address, after that it shows a progress bar..
