### ISSUE TITLE
Wallet Recovery ?

### ISSUE THREAD

**Issue by Jsep87** [ethereum/meteor-dapp-wallet#141]
Ok, So I did a windows 10 reset and chose to "keep files". Of course everything got deleted....
Luckily I was able to recover the deleted files with a program. 
What course of action do I need to take to get everything back to its original state? Just replace the mist folder and the keystore folder and I should be good?

Thanks for any advice,
Josh

**Comment by luclu** [comment]
@Jsep87 you just need the to recover the `keystore`-folder. Then just resync!
