### ISSUE TITLE
wallet crashed

### ISSUE THREAD

**Issue by azeino** [ethereum/meteor-dapp-wallet#143]
i am trying to use wallet 0.6.1, but when i try to import my presale file and after i entered my password the wallet was closed. !!!
i tried that many times and got the same result.

**Comment by frozeman** [comment]
will be fixed in the next version

**Comment by frozeman** [comment]
https://github.com/ethereum/mist/releases/tag/0.6.2

**Comment by Kryptolenko** [comment]
how to apply localization?

**Comment by frozeman** [comment]
? It detects your systems language.

**Comment by Kryptolenko** [comment]
my system language is Ukrainian. I saw a report that in previous versions has been added to the Ukrainian language. Is it possible to manually set the language?

**Comment by frozeman** [comment]
It should do it automatically. Open the console with CMD/CTRL + ALT + i and tell me what `navigator.language` gives you.

You set the language manually by typing `TAPi18n.setLanguage('ua')`
