### ISSUE TITLE
Mac OS El capitan (latest) Mist Wallet (latest) synchronization fails

### ISSUE THREAD

**Issue by neuroether** [ethereum/meteor-dapp-wallet#145]
More than two days and stuck on synchronization: Downloading block 1,229,707 of 1,308,295 for days. 
Tried using the terminal with geth and get a synchronization failed notice. Please help and thanks in advance

**Comment by luclu** [comment]
Does this problem still occur on verison `0.7.2` / geth `1.3.6`?
Can you please provide geths terminal output?

**Comment by neuroether** [comment]
Hi, I downloaded the latest Mist version 0-7-2 for MacOs. The wallet still does not synch it freezes while block synch. 
What I do is that I run latest version of geth --fast (1.4.0) from terminal and the open mist. 
Do you think this might be due to a pathway conflict? 

Thanks, 
Guido

**Comment by luclu** [comment]
I don't think this to be the cause.
The might be related to geth.
Can you please provide geths terminal output?

**Comment by neuroether** [comment]
Hi Luca, Mist is synchronising tough slow. Thanks for your help!

**Comment by frozeman** [comment]
We are aware of the slow syncing issue
