### ISSUE TITLE
Custom token balances no longer show

### ISSUE THREAD

**Issue by jorisbontje** [ethereum/meteor-dapp-wallet#149]
With 0.7.1 the custom token balances were initially no longer shown on either the account details screen (no `token-list`) or the custom token screen (0 value inside the wallet-box). On 0.6.1 they did show instantly.

After switching to testnet and back the token balances reappeared (so can't easily reproduce this).

**Comment by Beervangeer** [comment]
Hi there,

I got the same problem with 0.7.1.

![tokenreceived](https://cloud.githubusercontent.com/assets/521269/14716538/d1e0c410-07ed-11e6-84e2-415695f486bf.JPG)
![token0](https://cloud.githubusercontent.com/assets/521269/14716539/d1eb4be2-07ed-11e6-8c3b-aa16918bb140.JPG)

You can see the tokens being received here:
http://etherscan.io/token/MKR?a=0x699C9ee47195511f35f862ca4C22fD35ae8FfbF4

**Comment by Beervangeer** [comment]
I checked.
0.6.1 is indeed showing the token and I can send it !

**Comment by alexvandesande** [comment]
This issue has been fixed on development and will be released on a new version soon
