### ISSUE TITLE
suggestin: clickable pending wallet

### ISSUE THREAD

**Issue by debris** [ethereum/meteor-dapp-wallet#15]
It would be nice to have clickable wallet, that is still being created (pic 1). After opening it, there could be a NOTE like: "This wallet is still being created, please wait for XXX confirmations before using it." (pic 2).

pic 1
![screen shot 2015-06-09 at 12 42 49](https://cloud.githubusercontent.com/assets/2613714/8056189/fe2708d2-0ea5-11e5-8a6a-0b3c9576d67d.png)

pic 2
![screen shot 2015-06-09 at 12 49 19](https://cloud.githubusercontent.com/assets/2613714/8056188/fb12cfa0-0ea5-11e5-9897-9ade8d3b90e5.png)

**Comment by frozeman** [comment]
Thats on purpose, so users don't use the address until its fully confirmed. because you might  loose your money.
