### ISSUE TITLE
wallet password problem after moving from test-net to live

### ISSUE THREAD

**Issue by WMDwebs** [ethereum/meteor-dapp-wallet#150]
Node type: geth
OS: linux
Network type: main
Mist version: 0.6.2

I am new to Mist, so please pardon my ignorance.

I was running geth and Mist - initially ran Mist on test-net, no problems - I added accounts (2) and was able to transfer between them fine.

I then went to live, and had a friend send me a few eth so I could create a new account, after restarting the Mist browser, the eth showed in the main wallet. When I attempted to transfer funds to a new account - the "wrong password error" pops up.

 - the password was done by copy & paste from my KeePass, so I know there is no typo there.

Any clue what happened or how to fix this?

**Comment by alexvandesande** [comment]
Just to make sure, the account was created on the main net, right? You can try to unlock the account via the command line, but I would first check if the account you created is indeed the same as the password origin

**Comment by WMDwebs** [comment]
thank you for responding, I am not sure how else to verify the Passwords, I have done numerous searches here on GitHub to find tips & suggestions to help on this - again, I am new to this, so please pardon  my ignorance

**Comment by luclu** [comment]
Have a look at geths console commands as @alexvandesande suggested.
https://github.com/ethereum/go-ethereum/wiki/Managing-your-accounts

**Comment by WMDwebs** [comment]
Thank you,  I will check it out.

**Comment by luclu** [comment]
I will close this for now. If there is still a problem make sure to check out this summury: https://github.com/ethereum/mist/issues/669!
