### ISSUE TITLE
Synchronization stops after wallet UI comes up

### ISSUE THREAD

**Issue by nagydani** [ethereum/meteor-dapp-wallet#152]
Have not experienced this issue prior to 0.7.0. Running the Linux 64 bit version.

When starting up the wallet (w/o geth already running), it synchronizes to the blockchain alright, but then, despite being connected to a number of peers, it stops. The counter of time since last block just keeps going, effectively measuring the time since the last block at the time of starting the application.

In the log, the only error that I see happens during synching:
```
[2016-04-20 17:16:01.675] [WARN] nodeConnector - NODECONNECTOR ERROR { [Error: connect ECONNREFUSED /home/nagydani/.ethereum/geth.ipc]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '/home/nagydani/.ethereum/geth.ipc' }
Error: connect ECONNREFUSED /home/nagydani/.ethereum/geth.ipc
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
```

**Comment by nagydani** [comment]
The problem is still there with 0.7.1

**Comment by bas-vk** [comment]
When this happens could you:

1. determine if geth is stil running through the process explorer of the OS
2. and if runs try to connect to it with `geth attach` and report if this fails or not?

**Comment by nagydani** [comment]
1. Yes, geth is still running.
2. Attachment is successful. Moreover, the node actually remains connected (to a few dozen peers) and synchronized (block number are duly increasing), but the mist GUI reflects none of this.

**Comment by bas-vk** [comment]
Thanks for the information, this is very valuable. It seems that geth is actually working as expected but mist is for some reason not able to (re)connect. @hiddentao, any thoughts?

**Comment by hiddentao** [comment]
Yep, sounds like a bug in Mist. I think I'll dive into the Mist-geth sync as the next step as see if I can figure it out.

**Comment by frozeman** [comment]
@nagydani does the connection error show up right when yo start, or later after it tried to sync?

Because the one at start is not a problem, as its intended.

If you get one later, then it should be that you node has stopped, which it didn't. The https://github.com/ethereum/mist/blob/master/modules/checkNodeSync.js does actually use an interval to call the node for sync status, so it seems more like your node is actually NOT syncing..

Did you check if the block number grows?

**Comment by nagydani** [comment]
Only at start.
Yes, I checked that block numbers grow by `geth attach` and then `eth.blockNumber`. It does grow.

**Comment by luclu** [comment]
This should be fixed in recent versions.
