### ISSUE TITLE
suggestion: autocomplete 'TO' field in send tab

### ISSUE THREAD

**Issue by debris** [ethereum/meteor-dapp-wallet#16]
It would be nice to have autocomplete in 'TO' field in send tab (pic 1), so we could choose one of our wallets by name (pic 2).

pic1
![screen shot 2015-06-10 at 07 16 12](https://cloud.githubusercontent.com/assets/2613714/8075456/d5821fde-0f40-11e5-9572-027f5472addd.png)

pic2
![screen shot 2015-06-10 at 07 16 28](https://cloud.githubusercontent.com/assets/2613714/8075458/da4ef2b2-0f40-11e5-8d6d-92c7a35f2639.png)

**Comment by frozeman** [comment]
Will be done by mist.
