### ISSUE TITLE
Address wallet password!!!!!!!!

### ISSUE THREAD

**Issue by gciccol** [ethereum/meteor-dapp-wallet#163]
Hello, I downloaded the ethereum wallet file for MAC; I unzipped the file and I ran the ethereum wallet app. It opened and sync and I ALREADY FOUND A A MAIN ACCOUNT (ETHERBASE) without asking me any password creation. I deposited ether and now I wanted to move some of them IT ASKS ME A PASSWORD.
 What's going on????????

Please help!!!!!!!!!!!!!!!!!!!!

**Comment by luclu** [comment]
What version of the Wallet are you using?
Did you use any earlier version?
Did you use geth without the Wallet/Mist before?

**Comment by gciccol** [comment]
Hi Luca, i am using the last version 7. 1 and I didn't used geth on this machine. Furthermore I downloaded the wallet (still 7.1) on my Mac pro and it did the same thing. No password request and I have found a wallet with either on (not the same of the other one)

Besides I still can't access to my presale wallet and I am really sure about the passphrase. 
I am a good advocate of ethereum but what the heck I start feeling depressed. Please help me. 

Thank you 

Inviato da iPhone

**Comment by gciccol** [comment]
it seems as I downloaded together with the zip file someone else's wallet! In two different cases!

There is something weird here

**Comment by alexvandesande** [comment]
@gciccol where did you download this from?

**Comment by gciccol** [comment]
From ethereum.org

Inviato da iPhone

**Comment by luclu** [comment]
> it seems as I downloaded together with the zip file someone else's wallet! In two different cases!
--> version 0.7.2 was pushed to the webpage `ethereum.org` in the meanwhile. This might be your second wallet?

Or do you mean, that the etherbase account address changed?

**Comment by gciccol** [comment]
No it didn't change. It always was the same. I installed ethereum wallet on two different Mac. In the both cases as I ran the program it didn't asked me to set a password. In the first machine I deposit ether that I can't withdraw now, since it asks me password even if I haven't set. 
In the sec on machine it happened the same. But in this case I also found already several ether! 
It's really weird! 
I emailed helpdesk ethereum but no answer so far. And I still have issues with my pre sale wallet. 
I'm into cryptos since 2011 and I NEVER had these problems. Only with this ethereum. 

And I'm getting nervous. This happenings are stoling me a lot of money and I don't have any assistance.

**Comment by luclu** [comment]
Could you please provide the account address in question? (Please mind the privacy concerns on this)

**Comment by gciccol** [comment]
0xC75d2259306AEC7DF022768c69899a652185dBC4
This is the one I d/l in my mac pro; there are already 4000 ether! And
these are NOT mine!

0x03fD53231c28C89F3e24C4aDD145c8417A3a2445
And this is the one I d/l in my imac. It was empty and I made two deposits
one from one exchange smaller and one from another exchange. I bought ether
because I wanted to get into DAO. But it asks me password that I NEVER was
asked to set.

It's a nightmare. As I said I also have issue with opening my presale
wallet.




2016-05-05 2:01 GMT+02:00 Luca Zeug <notifications@github.com>:

**Comment by luclu** [comment]
@gciccol would you mind a screen-sharing session?

**Comment by gciccol** [comment]
OK I'm in gitter now

**Comment by gciccol** [comment]
Hi Luca, I unlocked my wallet (not the presale I'm afraid)!!!! Somehow I
inserted one of my password but with the caps lock on.

I am definetely fused LOL!

Thankyou again!!!!!!

2016-05-05 13:29 GMT+02:00 Luca Zeug <notifications@github.com>:

**Comment by luclu** [comment]
You are welcome. Please close this issue!
