### ISSUE TITLE
Ethereum Wallet in black screen

### ISSUE THREAD

**Issue by panicape** [ethereum/meteor-dapp-wallet#166]
Hi guys & girls, my wallet is not working, it is everything in black but if i move the mouse around the wallet it changes the icon, i supose that it means that the functionality is ok but i can't see anything

here is the screenshot:
![screen](https://cloud.githubusercontent.com/assets/3757255/15073428/aef89c86-1399-11e6-91d0-12b15c3fbb3d.png)

**Comment by luclu** [comment]
@panicape What version are you running? Have you tried version 0.7.2?

Related issues:
https://github.com/ethereum/mist/issues/75
https://github.com/ethereum/meteor-dapp-wallet/issues/78

**Comment by 5chdn** [comment]
Also http://ethereum.stackexchange.com/questions/2429/87

**Comment by panicape** [comment]
I tried the version 0.5.2 and 0.3.5 or 0.3.2 (i don't remember this 0.3 exactly)

**Comment by panicape** [comment]
@5chdn but this is another thread, at least them can see something, in my case since i start the wallet it is set in black screen

**Comment by 5chdn** [comment]
@panicape first thing to try is downloading the latest wallet. [try 0.7.2](https://github.com/ethereum/mist/releases)

Then, try to run mist or ethereum-wallet with the `--ignore-gpu-blacklist` flag. This might cause the client to crash. But if it does not crash, you probably run a working wallet by now.

**Comment by panicape** [comment]
and how can i do that? i usually start the wallet from the executable "Ethereum-wallet" inside its folder

**Comment by 5chdn** [comment]
create a `.bat` file with the following content:

    Ethereum-Wallet.exe --ignore-gpu-blacklist

And run it.

**Comment by panicape** [comment]
ok, i'm gonna try and i will say something

**Comment by panicape** [comment]
Yeaps, it works for me, it seems that it was similar to white screens problem, thanks @5chdn 
But your solution of creating a .bat is for windows, i'm using Ubuntu 15.10. In this case, i create a shell file with this parameters inside:
#!/bin/bash
echo running the Ethereum Wallet
./Ethereum-Wallet --ignore-gpu-blacklist

and i put the shell file inside the same folder of the wallet

**Comment by luclu** [comment]
If affected please look here: #599
Make sure to update to 0.7.4.
Further discussion will happen over here: #75
I will close this as duplicate.

Thank you @panicape I will append this to #599!
