### ISSUE TITLE
Bounty offered for help

### ISSUE THREAD

**Issue by klm23** [ethereum/meteor-dapp-wallet#167]
I can't get Mist 7.2 to work on my win10 64 machine.  Posted all over the place, tried adjusting firewalls using a VPN, etc., etc...getting tired of writing about what is wrong and uploading screen shots. I am very heavily invested in ETH and The DAO crowdsale.  Is there someone to whom I can please offer an ethereum bounty ahead of time to call me and trouble shoot with me over the phone?

**Comment by alexvandesande** [comment]
Hi KLM, sorr This is the first time I see this. Do you have a link to a place you already posted screenshots and a longer description?

Heads up: if you're using 7.2 don't add the dao contract to your watched contracts list as it will freeze up the interface. If that's the case I suggest you download version 0.6 and remove the dao. You can still send money to it.

**Comment by klm23** [comment]
Thanks for your response

here is a link which has some images and explanations.

 https://github.com/ethereum/mist/issues/545

 I did try to track the contract but I don't think anything happened because the app never synced--not sure how to get it out of watched contracts--but big worries described below--same happens when I try the older wallet.  No idea how to start from scratch.  Please let me send you bounty and talk over phone and/or share my computer to you.

**Comment by 5chdn** [comment]
@klm23 what does the [node logs](http://ethereum.stackexchange.com/q/3365/87) say? could you paste them somewhere?

**Comment by klm23** [comment]
Thanks for your response

I0503 22:12:59.574948   17280 database.go:71] Alloted 433MB cache to C:\Users\Ken\AppData\Roaming\Ethereum\chaindata
I0503 22:12:59.622993   17280 database.go:71] Alloted 78MB cache to C:\Users\Ken\AppData\Roaming\Ethereum\dapp
I0503 22:12:59.648018   17280 backend.go:314] Protocol Versions: [63 62 61], Network Id: 1
I0503 22:12:59.649019   17280 backend.go:362] Blockchain DB Version: 3
I0503 22:12:59.649019   17280 blockchain.go:214] Last header: #0 [d4e56740…] TD=17179869184
I0503 22:12:59.649019   17280 blockchain.go:215] Last block: #0 [d4e56740…] TD=17179869184
I0503 22:12:59.649019   17280 blockchain.go:216] Fast block: #0 [d4e56740…] TD=17179869184
I0503 22:12:59.654023   17280 cmd.go:115] Starting Geth/v1.3.6/windows/go1.5.1
I0503 22:12:59.654023   17280 server.go:311] Starting Server
I0503 22:13:01.998277   17280 nat.go:111] mapped network port udp:30303 -> 30303 (ethereum discovery) using UPNP IGDv1-IP1
I0503 22:13:02.114387   17280 udp.go:212] Listening, enode://c8a3da54217a18f4bb99adbf0aa62407cd7995a55ed38b34a996d292cb0b0a06fc900a668f562773505cfc70653ab0fce89b08680c85d09a236afaedb1dde889@10.0.0.250:30303
I0503 22:13:02.114387   17280 backend.go:526] Server started
I0503 22:13:02.114387   17280 ipc.go:112] IPC service started (\\.\pipe\geth.ipc)
I0503 22:13:02.115388   17280 server.go:552] Listening on [::]:30303
I0503 22:13:02.119393   17280 nat.go:111] mapped network port tcp:30303 -> 30303 (ethereum p2p) using UPNP IGDv1-IP1

**Comment by 5chdn** [comment]
and after letting it run for lets say 30 minutes, nothing more appears in the logs?

**Comment by klm23** [comment]
Correct it ran for a day once--and many hours a second time.  Never saw anything syncing in terms of percentages achieved.

**Comment by 5chdn** [comment]
Best to do now is reporting it over at the geth repository and link this issue from there:

https://github.com/ethereum/go-ethereum/issues/

**Comment by klm23** [comment]
I did that already, days ago--no solution with them (and I'm not running Win32)--they gave up on mt when the common troubleshooting tips didn't work, like try a VPN, check your firewall, etc.--that is why I am offering a bounty to someone in the know to help me directly--get on the phone with me, connect to my computer and see what I have or haven't done.

**Comment by klm23** [comment]
Issue resolved--Windows clock needed to resync--many thanks to 5chdn!:)

**Comment by 5chdn** [comment]
your welcome. for future reference, the issue was: https://github.com/ethereum/mist/issues/94 a.k.a. `no seed nodes found`. Had to start the client with verbosity `9` to get to that message.
