### ISSUE TITLE
Readability of messages in the splash dialog is severely impaired by choice of background and foreground colors

### ISSUE THREAD

**Issue by nagydani** [ethereum/meteor-dapp-wallet#172]
![screenshot from 2016-05-10 12 35 05](https://cloud.githubusercontent.com/assets/374934/15143864/24da1f64-16ac-11e6-94d1-b69ef7385f38.png)

**Comment by luclu** [comment]
related: https://github.com/ethereum/mist/issues/598

**Comment by luclu** [comment]
closed as duplicate.
