### ISSUE TITLE
Watching "The DAO" contract makes Mist unresponsive

### ISSUE THREAD

**Issue by shoraibit** [ethereum/meteor-dapp-wallet#174]
See CPU profile (32MB) https://s3.amazonaws.com/shoraibit/CPU-20160511T002536.cpuprofile

Would appreciate a quick work around for this until this issue is resolved.

**Comment by luclu** [comment]
Thank you for reporting! This has already been fixed in `develop` and will be available in the next release.
Here are those pull-requests:
https://github.com/ethereum/meteor-dapp-wallet/pull/161
https://github.com/ethereum/meteor-dapp-wallet/pull/165
