### ISSUE TITLE
Enhancement : add "add wallet contract" button

### ISSUE THREAD

**Issue by olivierstern** [ethereum/meteor-dapp-wallet#176]
Add an "Add Wallet contract" button after the list of wallets contracts

**Comment by luclu** [comment]
@olivierstern what version are you currently running? There has been a bug in earlier version of the Ethereum-Wallet. Please give me a small ping-back if version 0.7.3 resolves this.

**Comment by olivierstern** [comment]
I'm running the very last one ! The 0.7.3

**Comment by luclu** [comment]
This should be available in 0.7.3:

<img width="600" alt="bildschirmfoto 2016-05-26 um 16 58 11" src="https://cloud.githubusercontent.com/assets/10135872/15579021/2195fb8e-2363-11e6-9100-d5c8cc70445e.png">

What backend are you using `geth` or `eth`?

**Comment by luclu** [comment]
The "add contract wallet" button will only be displayed if your funds are at least at 1 Ether as displayed in the corresponding description.
