### ISSUE TITLE
Wallet contract deletion not working

### ISSUE THREAD

**Issue by olivierstern** [ethereum/meteor-dapp-wallet#177]

**Comment by luclu** [comment]
Please provide these information: 
Node type: geth/eth
OS: linux/windows/osx
Network type: main/test
Mist version: 0.0.0

**Comment by olivierstern** [comment]
Node type : geth
OS : OSX 10.11.4
Network Main
Mist 0.7.3

**Comment by alexvandesande** [comment]
Olivier, I can't reproduce this behavior, can you please describe the steps you took to delete the wallet contract, what happened and what you expected to happen?

**Comment by olivierstern** [comment]
I added the wallet in the previous version of Mist, then renamed it.
I click on it, then click on the trash icon. I'm prompted to type the name of the contract wich I assume is the given name. I paste the name and press enter. I tried to paste the address also. I press OK but nothing happens. It remains in the list even if I relaunch the app.
I had anotherone I tried to delete without success and I executed the kill function to see what would happen. It is still in my list aswell but grey and undeletable !

**Comment by luclu** [comment]
@olivierstern I'm not sure about previous versions but in 0.7.4 you will need to type/paste `delete`. Does this work for you?

**Comment by olivierstern** [comment]
I got rid of it deleting the application support > mist files and reinstalling the last build. Let me try 2 things
- Add new wallet contract and delete it
- Add new wallet contract, kill it and delete it
I'll get back to you with the results

**Comment by olivierstern** [comment]
I have an IPC connection error for the moment I need to solve before I am able to do my tests :)

**Comment by olivierstern** [comment]
I rebuild from the develop branch and reinstalled it and it works. I changed the french translation file with the word "delete". Pasting the address rather than the word "delete" would be maybe better in order to make it translatable, no ?
