### ISSUE TITLE
New and Fucking Lost - Would Appreciate Some Help

### ISSUE THREAD

**Issue by always-sunny** [ethereum/meteor-dapp-wallet#187]
So, I downloaded ethereum-wallet 7.3. I created an account with Coinbase, purchased .0369 bitcoin, then attempted to buy ether using ShapeShift. I put the .0369 bitcoin in and for the delivery ether address I put the address of my Main Account(etherbase) on the ethereum wallet because apparently I need at least 1 ether to start doing things. The transaction went through and on etherchain it shows that my MainAccount(etherbase) has the 1.4~ ether but in my ether wallet it doesn't appear and I really don't know what to do. Also, how tf do you delete accounts and wallets on the ethereum-wallet? I was messing around and created two additional accounts that I don't want/need. 

Thanks for your time guys.

**Comment by alexvandesande** [comment]
You don't need 1 ether to do things, only to create an Contract Wallet.
