### ISSUE TITLE
Multisig support for subtokens

### ISSUE THREAD

**Issue by taoteh1221** [ethereum/meteor-dapp-wallet#193]
Moved this from the Mist repo at the request of @luclu : https://github.com/ethereum/mist/issues/660

> It would be really great if there was a multisig security option to protect subtokens (TheDAO, Unicorns, etc)? I believe right now there is not an available security option yet for subtokens in multisig wallets?

**Comment by olivierstern** [comment]
That's a good point. Daily minimum withdraw applies to ether, not tokens. Maybe add a setting that requires or doesn't require confirmations regardless of the amount ?

**Comment by taoteh1221** [comment]
@olivierstern I think they'd model it after their current ETH multisig, so no extra sigs àre required below a certain amount for subtokens as well.

**Comment by olivierstern** [comment]
You would need then to add a setting per token which is not doable with a standard wallet contract, because otherwise with a single minimum setting for all tokens it is irrelevant, because the intrinsic value of the tokens can vary a lot from one another, or I miss something ? Then to me the best solution to keep it simple is to allow or ban token transfer without confirmation.

**Comment by taoteh1221** [comment]
@olivierstern No clue myself, hopefully they come up with something good. :smile:

**Comment by luclu** [comment]
This designated new wallet contract will require any non-Ether-token to be confirmed regardless of the amount: 
https://github.com/ethereum/dapp-bin/pull/62 
https://github.com/ethereum/mist/issues/783

**Comment by taoteh1221** [comment]
@luclu Great news. Has this been included in Mist v0.7.6 wallet contract deployment, or do I have to wait for a future Mist release?

**Comment by luclu** [comment]
The ETA is currently 1.0 - but this is more a symbolic milestone. Expect this to be be introduced earlier.

**Comment by olivierstern** [comment]
Very good news !! Nice job

**Comment by taoteh1221** [comment]
Awesome, thanks for all your hard work. :+1:

**Comment by luclu** [comment]
FYI https://github.com/ConsenSys/MultiSigWallet will have token support. We are looking forward to switch to this wallet.

**Comment by taoteh1221** [comment]
@luclu Awesome. Looking forward to securing ERC20 crowdsale tokens. Any specifics yet on what version of Mist will have this?

**Comment by luclu** [comment]
As it is still work in progress and didn't undertake any serious audit yet I **don't** expect it to be included in the next 1-2 months. Though I would love to see it sooner than later.

**Comment by taoteh1221** [comment]
Thanks very much for your responses. :)

**Comment by taoteh1221** [comment]
Has the default Mist multisig been upgraded to secured ERC20 token support yet, regarding X of X sigs required for ERC20 token withdrawals?
