### ISSUE TITLE
Disallow transactions to the same wallet account

### ISSUE THREAD

**Issue by luclu** [ethereum/meteor-dapp-wallet#194]
Disallow send coins from ACC1->ACC1.
Check if wallet Outgoing have same address Incoming wallet.

Moved from: https://github.com/ethereum/mist/issues/567

**Comment by luclu** [comment]
PR: https://github.com/ethereum/mist/pull/994

**Comment by frozeman** [comment]
I didn't saw this issue, but saw that to prevents me to send to my own account, whats the reasoning behind that? I can see a lot of use cases in sending to its own account, e.g. a contract executing functions on itself
