### ISSUE TITLE
Adding an authorise boolean for token transaction in multisig wallet contract

### ISSUE THREAD

**Issue by olivierstern** [ethereum/meteor-dapp-wallet#203]
It would be a great feature to add a boolean in the multisig wallet contract that prevent transaction of token without the confirmation requirements in order to protect the tokens owned by the contract. For the moment it is only possible to set a max ether per day. Since there might be many different tokens with different value, a simple yes or no authorization field to allow or prevent token transaction without confirmations would be a great feature fo securing tokens. What is your opinion ?

**Comment by luclu** [comment]
Related to *multisig subtoken support* (https://github.com/ethereum/meteor-dapp-wallet/issues/193).

**Comment by luclu** [comment]
> https://github.com/ConsenSys/MultiSigWallet will have token support. We are looking forward to switch to this wallet. 

I will close this in favour of https://github.com/ethereum/meteor-dapp-wallet/issues/193
