### ISSUE TITLE
Error creating Ethereum Wallet - please help !!!

### ISSUE THREAD

**Issue by jadeazul8** [ethereum/meteor-dapp-wallet#209]
now is my second week trying to create Ethereum Wallet  -  I got " error "
 "no node or Ethereum binaries found "
no matter what I do, code or instruccions I have followed.  
Since  I am not a java expert or programer,I need help.

   Could some one tell me how, I could create wallet ??

**Comment by alexvandesande** [comment]
Are you using windows 32 bits? Then unfortunately you'll have to install
more software: ethereum.org/cli

On Wed, Jun 1, 2016 at 11:39 AM, jadeazul8 <notifications@github.com> wrote:

> now is my second week trying to create Ethereum Wallet - I got " error "
> "no node or Ethereum binaries found "
> no matter what I do, code or instruccions I have followed.
>
> Since I am not a java expert or programer,I need help.
>
> Could some one tell me how, I could create wallet ??
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ethereum/meteor-dapp-wallet/issues/209>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AAG5AiYRPsI8r2itLiz_xnsAxm93_JZbks5qHZm1gaJpZM4Irnph>
> .
>



-- 

Alex Van de Sande
UX Designer

**Comment by luclu** [comment]
I will close this for now.
