### ISSUE TITLE
Unable To Get Electron-Prebuild To Install ?

### ISSUE THREAD

**Issue by bitprospector** [ethereum/meteor-dapp-wallet#211]
My OS is Debian Jessie Amd64 w/Iceweasel (Firefox) Browser.

I have npm, npm2deb & nodejs (not  nodejs-legacy) installed.

I'm unfamiliar with java & javascript.

I've been trying for a week to get electron-prebuild to install
no luck so far error:
-----------------------------------------------------
sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! electron-prebuilt@1.2.1 postinstall: `node install.js`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the electron-prebuilt@1.2.1 postinstall script.
npm ERR! This is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "electron-prebuilt" "--save-dev"
npm ERR! cwd /home/mel/mist
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/mel/mist/npm-debug.log
npm ERR! not ok code 0
--------------------------------------------------
I tried npm install -g electron-prebuilt@0.37.2 first, and
then just electron-prebuild to try for newest version.
Neither one will install ?

Until it becomes easier to set up a "Mist Wallet", it probably
won't be widely used.

Any suggestions would be greatly appreciated.

bitprospector.

**Comment by luclu** [comment]
make sure you have node > 4.4 installed.
`sudo apt-get install nodejs npm`
check `node --version`
you might need to `ln -s /usr/local/bin/node /usr/loca/bin/nodejs`

electron-prebuilt can be aquired from [npmjs.org](npmjs.org) with `npm install -g electron-prebuilt@1.0.1` for current `develop` branch of **Mist**. This will install **electron** and source it.

from there you will only run `electron .` to launch mist. Stick to the readme for further instructions.

**Comment by bitprospector** [comment]
I followed your suggestions above, but still won't install.

Got basically same errors:
npm install -g electron-prebuilt@1.0.1
npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine hawk@3.1.3: wanted: {"node":">=0.10.32"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.29","npm":"1.4.21"})
/usr/local/bin/electron -> /usr/local/lib/node_modules/electron-prebuilt/cli.js

> electron-prebuilt@1.0.1 postinstall /usr/local/lib/node_modules/electron-prebuilt
> node install.js

sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! electron-prebuilt@1.0.1 postinstall: `node install.js`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the electron-prebuilt@1.0.1 postinstall script.
npm ERR! This is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "electron-prebuilt@1.0.1"
npm ERR! cwd /home/mel/mist
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/mel/mist/npm-debug.log
npm ERR! not ok code 0

bitprospector
