### ISSUE TITLE
Accounts not added to EthAccounts correctly

### ISSUE THREAD

**Issue by runn1ng** [ethereum/meteor-dapp-wallet#220]
I have tried to run developer version of mist and meteor-dapp-wallet, and whenever I try to add account, they don't appear.

I have tried to locate the issue. It seems to be somewhere in `upsert` and/or `update` in `meteor-package-accounts`. An example:

[Here](https://github.com/ethereum/meteor-dapp-wallet/blob/master/app/client/templates/views/dashboard.js#L96-L99) in dashboard.js there is this code:

```javascript
EthAccounts.upsert({address: account}, {$set: {
    address: account,
    new: true
}});
```

When I add log after that, it seems that nothing is added!

```javascript
EthAccounts.upsert({address: account}, {$set: {
    address: account,
    new: true
}});
var accounts = EthAccounts.find().count()
console.log("done", accounts); // print 0
```

However, it seems that it is in findAll

```javascript
EthAccounts.upsert({address: account}, {$set: {
    address: account,
    new: true
}});
var accounts = EthAccounts.findAll().count()
console.log("done", accounts); // print 20 (and adding each iteration)
```

And if I print findAll, it seems some Mongo-ese stuff is added 
```javascript
EthAccounts.upsert({address: account}, {$set: {
    address: account,
    new: true
}});
var accounts = EthAccounts.findAll().fetch()
console.log("done", accounts); 
```
prints things like this (all of them look like this):

```javascript
{ _id: 'bKdMnnkpTMFxcjHDC',
    address: '0x04c1cc878b766ab7f1103289bc1d06bd1dc68f68',
    deactivated: { '$exists': false },
    new: true },
```

This doesn't seem correct at all, this looks like the mongo query gets saved into storage by mistake.

It seems it's because of [this, in meteor-package-accounts](https://github.com/ethereum/meteor-package-accounts/blob/master/accounts.js#L194-L196)

```javascript
EthAccounts.update = function(){
    return this._collection.update.apply(this, this._addToQuery(arguments));
};
```

where addToQuery adds mongo magic to the query.

But I am not sure how to change code of running app in meteor, and monkey-patching it broke other things, so that might or might not be it.

**Comment by runn1ng** [comment]
I am also not sure why it happens only in the dev version and not in the released binary version.

**Comment by luclu** [comment]
@runn1ng make sure to pull the latest changes on both repos. There were some issues while changing the database some days ago.

**Comment by runn1ng** [comment]
Yep, that fixed it. (And now I have 50 accounts.)

**Comment by runn1ng** [comment]
I know that this is a general question and not a bug/issue, but... how exactly do I delete an account?

**Comment by luclu** [comment]
Currently you will have to go to menu -> accounts -> backup -> accounts and delete the corresponding file. The changes reflect after you restart or switch to another view in the wallet.

**Comment by runn1ng** [comment]
That worked, thanks

**Comment by luclu** [comment]
You are welcome.
Alternatively you could also interact with the keystore through `web3.personal` on the console.
