### ISSUE TITLE
Possible to drag & drop wallet's nav buttons

### ISSUE THREAD

**Issue by luclu** [ethereum/meteor-dapp-wallet#222]
It shouldn't be possible to drag&drop the buttons "Send", "Contracts", etc.

**Comment by alexvandesande** [comment]
Ive added drag to the whole header. I can remove from the buttons but.. Why not?

**Comment by luclu** [comment]
ah that will do.
There is just no point in dragging the send-button on the desktop to create some link to `file:///send.html` :P
