### ISSUE TITLE
send all -> negative amount

### ISSUE THREAD

**Issue by luclu** [ethereum/meteor-dapp-wallet#223]
This seems to happen when the account's balance is smaller than the specified fee.
Trying to send will alert the user with "wrong password".

<img width="1031" alt="unbenannt-1" src="https://cloud.githubusercontent.com/assets/10135872/16077587/1f32e086-32fa-11e6-9d72-33f0bec3fdb8.png">

This could be responsible for some of the user's "password issues".

**Comment by alexvandesande** [comment]
Never seen this. Weird indeed.

**Comment by luclu** [comment]
You can also trigger the "wrong password" alter by creating an new account without any balance and try to create a contract wallet with it.

**Comment by frozeman** [comment]
The wrong password issue, might just be because we can't map errors, but the negative balance in your screenshot is very weird.

**Comment by luclu** [comment]
No check if account's `balance > fee` ([send.js#L317](https://github.com/ethereum/meteor-dapp-wallet/blob/develop/app/client/templates/views/send.js#L317))
