### ISSUE TITLE
0 peers __ waiting for blocks

### ISSUE THREAD

**Issue by arotello** [ethereum/meteor-dapp-wallet#225]
Node type: geth 1.4.7
OS: OS X El Capitan (10.11.5)
Network type: main
Mist version: 0.7.5

I upgraded Mist, deleted the original blockchain (~13GB) and let the new version sync (~4.3GB)  After syncing, the Mist application opens up but shows 0 peers __ waiting for blocks.  This lasts for around 30 min before peers and blocks suddenly appear.  However, Mist then says X number of minutes since last block and never syncs.  At this point, the application isn't frozen but blocks never update.  Starting up geth before opening Mist does not resolve the issue.  Geth is running as expected in the background.

**Comment by luclu** [comment]
Thank you for reporting @arotello, could you kindly copy/reopen this issue on the mist repo? https://github.com/ethereum/mist/issues
I will close this here afterwards.

**Comment by arotello** [comment]
done, thanks

**Comment by luclu** [comment]
awesome 👍
