### ISSUE TITLE
I am now using the ether currency to the docking site

### ISSUE THREAD

**Issue by lvaluoliwei** [ethereum/meteor-dapp-wallet#227]
My website is: www.caoyy.com
How can I connect my trading website with your money?
I can butt my other currency trading platform, I only need to configure the%appdata%conf file on the line
But I do not know how you set up this?

My QQ mailbox is: 2315637385@qq.com

**Comment by luclu** [comment]
You are best advised to hire some professional software engineer/consultant to figure out the best approach to integrate this into your portfolio. We can't serve you this support in the issues of a network client frontend..
