### ISSUE TITLE
Synchronisation Geth-ethe

### ISSUE THREAD

**Issue by butchy19** [ethereum/meteor-dapp-wallet#236]
Bonjour

Mon portefeuille ethereum ne se synchronise pas, voila le message que j'ai:
Ethereum my portfolio does not sync, here is the message I:

`I0703 12:42:43.072976 eth/downloader/downloader.go:299] Synchronisation failed: uncle[0](ec63b35f)'s parent is not ancestor (bd092bcd)
E0703 12:42:53.491727 core/blockchain.go:1128] Bad block #1394648 (0x23d9a45308a8b37a50b174a409125fc61b23ad44dae3fe10624007e42de77cac)
E0703 12:42:53.491727 core/blockchain.go:1129]     uncle[0](ec63b35f)'s parent is not ancestor (bd092bcd)`

Avez vous une solution?
Merci
Do you have a solution?
Thank you

**Comment by luclu** [comment]
You should be able to ignore this message. 

What block are you at now?
Could you please upload your node's log in a zip?

**Comment by butchy19** [comment]
Merci, 

Mais j'ai supprimé le dossier chaindata, maintenant il synchronise depuis le début, j’espère qu'il n’arrêtera pas comme il l'a fait au block 1 394 648 

Thank you, 
but I deleted the  folder chaindata, now sync from the beginning, I hope it will not stop as it did in Block 1394648

**Comment by butchy19** [comment]
Je garde le post ouvert jusqu’à la fin de la synchronisation

I keep the post open until the end of the synchronization

**Comment by butchy19** [comment]
Merci il est a nouveau synchronisé
