### ISSUE TITLE
Lost wallet after refresh mist

### ISSUE THREAD

**Issue by obscuren** [ethereum/meteor-dapp-wallet#24]
Created a single address wallet: `{"data":{"type":"wallet","owners":["0xe6716f9544a56c530d868e4bfbacb172315bdead"],"name":"Main","balance":"999000000000000000000","creationBlock":898497,"disabled":true,"address":"0xe636b5701367f5a7f8f04db07142c265d0128057","transactions":["tx_aa360bfa13","tx_eaf75b0358"],"_id":"8JuKjwDPvCdzk5aPx"},"expires":null}` is the wallet in minimongo.

The wallet disappeared after refreshing

**Comment by frozeman** [comment]
Reminder: create contract to store wallets associated with accounts, and add backup options.
