### ISSUE TITLE
Create 404 page redirect for hosted site

### ISSUE THREAD

**Issue by alexvandesande** [ethereum/meteor-dapp-wallet#240]
On the wallet, doing a refresh anywhere but the main page with create a 404 because the files are not handles by meteor so the location does not connect to the actual file path.

A solution would be to create a 404 redirecting all pages to the initial one.

https://help.github.com/articles/creating-a-custom-404-page-for-your-github-pages-site/

**Comment by luclu** [comment]
Current workaround: open base URL https://wallet.ethereum.org

**Comment by luclu** [comment]
PR: https://github.com/ethereum/mist/pull/1026
