### ISSUE TITLE
fix <em> tags in i18n

### ISSUE THREAD

**Issue by luclu** [ethereum/meteor-dapp-wallet#243]
As this PR https://github.com/ethereum/meteor-dapp-wallet/pull/226 broke html tags they are currently displayed as plain text.

<img width="984" alt="bildschirmfoto 2016-07-23 um 19 54 21" src="https://cloud.githubusercontent.com/assets/10135872/17079389/52f84432-510f-11e6-8f82-2066e3c97bdb.png">

**Comment by evertonfraga** [comment]
Done in commit: 
https://github.com/ethereum/meteor-dapp-wallet/commit/2b1b8707d34ac86abaeff77a5d8bc970985f8817

already in develop branch.
