### ISSUE TITLE
wallet problem

### ISSUE THREAD

**Issue by sakis123** [ethereum/meteor-dapp-wallet#251]
Hi i have many problems with the wallet.
I make yesterday a transaction from my wallet to another account which i have , i see until now from the wallet  5.000 Confirmations but the coins never go to my other account. i did not make any mistake to the address.
I see from the etherchain that my balance is 22 ether but from my wallet i don't see this balance.
I create a second address from the wallet i make a transaction from the 1st address to the 2nd the coins transfered but from the etherchain i get the message for the 2nd address:  Error: Account not found!
what happened ?
Sorry for my English

**Comment by luclu** [comment]
Please have a look at https://github.com/ethereum/mist/issues/1017#issuecomment-234735982.
