### ISSUE TITLE
ethereum-dapp-wallet.meteor.com webpage not available

### ISSUE THREAD

**Issue by AdamMiltonBarker** [ethereum/meteor-dapp-wallet#264]
Hi guys just having a look around have a project planned and taking my first steps with ethereum.  I have downloaded the IDE's etc (MAC) but I am getting ethereum-dapp-wallet.meteor.com webpage not available in Mist, any ideas what may be happening.

**Comment by alexvandesande** [comment]
We are not using that anymore. Update your mist version and yowl be redirected to wallet.ethereum.org
