### ISSUE TITLE
 Please help -- its been 3 days, cant access ether in MAIN ACCOUNT (Ethereum Wallet)

### ISSUE THREAD

**Issue by JohanConradie24** [ethereum/meteor-dapp-wallet#265]
Hi there,

I am new to this, and lost, I installed Ethereum-Wallet-win64-0-8-1 and then send ether to
my “MAIN ACCOUNT (ETHERBASE)” in my Ethereum Wallet

I have problems accessing my ether in my “MAIN ACCOUNT (ETHERBASE)” in my Ethereum Wallet

 I have send ether to my “MAIN ACCOUNT (ETHERBASE)” in my Ethereum Wallet, and confirmed that the ether is in the account address via https://etherchain.org/account/0x7351a8e1f783df9835b06a716311e7789b0e9752#txreceived

BUT I cant see or access the ether from my Ethereum Wallet? What am I doing wrong?

Please help me get access to the ether in my MAIN ACCOUNT,  I have been battling to sort this out with no success the last 3 days

Thank you very much for your time and assistance in this matter.

Best Regards

Johan

**Comment by luclu** [comment]
@JohanConradie24 it seems you synced to the non-fork chain. Please head over to this small guide to get you going again: 
> I want to sync to the HF chain but ended on the non-fork chain; Ether is missing #1028
