### ISSUE TITLE
--oppose-fork shows wrong ticker

### ISSUE THREAD

**Issue by AltronixLinq** [ethereum/meteor-dapp-wallet#267]
When connecting to a node with the --oppose-fork flag.  UI shows wrong ticker on wallet.

**Comment by luclu** [comment]
Could you kindly elaborate on what ticker you mean?
These ones are greyed out if an external instance is launched - as Mist is not in control of the node: 

<img width="547" alt="unbenannt-1" src="https://cloud.githubusercontent.com/assets/10135872/17323791/b7dcd66a-58a3-11e6-9984-f21431afa9bd.png">

**Comment by AltronixLinq** [comment]
Hello, appologies for being vague.

It looks like price ticker data is hardcoded to cryptocompare.com sym=ETH...  When running wallet on testnet, ETC, and private chains, the balence is always converted to ETH. In some cases this might be incorrect.

**Comment by luclu** [comment]
There will be an opt out in future releases: https://github.com/ethereum/mist/issues/199
Though we won't support ETC - head over to there repo instead: https://github.com/ethereumproject/mist
