### ISSUE TITLE
Lack of consistency among decimal numbers

### ISSUE THREAD

**Issue by evertonfraga** [ethereum/meteor-dapp-wallet#268]
On Mist sidebar it's shown 0.017 ETH; on the price ticker 10.02 ETH. In order to not cause confusion, we could adopt a consistent amount of decimal units to show — and maybe even avoid roundups, even tho i know it might be a long discussion.

![screenshot 2016-08-03 14 50 23](https://cloud.githubusercontent.com/assets/47108/17376800/8111634a-598d-11e6-8035-84d9dfa32223.png)

**Comment by frozeman** [comment]
Then we should simply report the same number to the sidebar, then we do show in the header.

**Comment by alexvandesande** [comment]
Agree. It makes sense for the sidebar and header to have the same amount of numbers. We don't need full precision there (unlike on the wallet account page)

**Comment by evertonfraga** [comment]
Now using two decimal units. 2a3b104349f8645359a16f6d4d2db53b99e54f0d
