### ISSUE TITLE
Dapp icons not updated properly

### ISSUE THREAD

**Issue by evertonfraga** [ethereum/meteor-dapp-wallet#269]
Steps to reproduce: 
1. Click on one watched contracts and memorize its Dapp icon.
   ![image](https://cloud.githubusercontent.com/assets/47108/17379021/d168193e-5996-11e6-9a40-a98e85005a00.png)
2. Click on Send section. The dappIcon shown belongs to the contract, not to "Account 2".
   ![image](https://cloud.githubusercontent.com/assets/47108/17379030/dd7bc32e-5996-11e6-864e-728d30b62a68.png)

**Comment by stvenyin** [comment]
know.

**Comment by stvenyin** [comment]
it.
