### ISSUE TITLE
Parity Geth mode: Contract interface does not appear either in Mist wallet nor Mist in Parity home screen.

### ISSUE THREAD

**Issue by ferni** [ethereum/meteor-dapp-wallet#279]
I've run into this issue running the wallet using Parity with --geth mode, instead of the geth client. I had submitted an issue in the Parity repo and had concluded that it was probably a bug in the Ethereum Wallet or Mist. 

Here's the issue in Parity repo: https://github.com/ethcore/parity/issues/1913

I'm pasting my submission here, which has more details:

> The button "Show contract info" that's in Mist's contract screen, which opens the options for interacting with the contract, does not appear. I've tried running "parity --geth", using the Ethereum Wallet software (Ubuntu), as well as using Parity's home screen to access the Ethereum Wallet from the browser. In both cases the section for interacting with a watched contract does not appear. I tried this when attempting to split ETC funds , using the splitter contract. I've tried using this contract both in the ETH chain as well as the ETC chain.

**Comment by alexvandesande** [comment]
Can you do me a favor and do the following:

1) menu develop > toggle developer consoles > Wallet
2) Type web3.eth.getCode('YOURADDRESS')

And tell me if it replies

Thanks!

**Comment by ferni** [comment]
So, it's working on Ethereum Wallet 0.8.2 but for the record:

The command did not reply on 0.8.1, the command replied on 0.8.2 ("0x").

The issue seems to be fixed on 0.8.2, I can properly see the contract info. So I guess you can close it :)
