### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by tomcoss** [ethereum/meteor-dapp-wallet#289]
Updated Mist wallet, can't see prior Eth. How do I change the ipcpath back to the original one?

**Comment by luclu** [comment]
Hi @tomcoss,
are your accounts available in the wallet? 
If you used different datadirs chances are you will have as many keystore folders as datadirs.

Please explain your issue in a little more detail, so I can better help you.

**Comment by luclu** [comment]
Closed as of inactivity.
