### ISSUE TITLE
[ meteor update so long  ]

### ISSUE THREAD

**Issue by windowz1** [ethereum/meteor-dapp-wallet#304]
I'm new on meteor-dapp-wallet.
I git clone & run geth node & cd meteor-dapp-wallet/app & meteor
...
Then 
$ meteor
[[[[[ ~/work18/meteor-dapp-wallet/app ]]]]]   

=> Started proxy.                             
=> Started MongoDB.                           
=> Meteor 1.4.2.3 is available. Update this project with 'meteor update'.
     Downloading xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx yy% zz.aa

so long. :-(

**Comment by luclu** [comment]
Unfortunately loading all the dependencies does take quite a while. If it stuck try to abort and issue the `meteor` command again.

**Comment by luclu** [comment]
I will close this for now.
