### ISSUE TITLE
Token transfer without populating the bytecode input-field causes invalid TX

### ISSUE THREAD

**Issue by luclu** [ethereum/meteor-dapp-wallet#305]
Used Token: https://ethereum.org/token

Not pressing "show more options" will cause an invalid TX with **input data:** `0x` ([etherscan: TX](https://etherscan.io/tx/0x91c83aa83de5e507454cf1d58615069ef1dd25183c1652c9e035ff723700d46c))

Also the wallet will warn about it:

<img width="582" alt="bildschirmfoto 2016-12-01 um 16 49 11" src="https://cloud.githubusercontent.com/assets/10135872/20800709/b481bae2-b7e6-11e6-8463-1c28dca5d339.png">

**Comment by frozeman** [comment]
fixed in 4f4c355
