### ISSUE TITLE
can't deploy a contract: Uncaught SyntaxError: Unexpected token u in JSON at position 0(…)

### ISSUE THREAD

**Issue by cdetrio** [ethereum/meteor-dapp-wallet#306]
The error is on [compileContract.js#L178](https://github.com/ethereum/meteor-dapp-wallet/blob/894bd90846d5b34fc44a2397cbecc19590fe9f8b/app/client/templates/elements/compileContract.js#L178).

It seems to be expecting an old result format from `web3.eth.compile.solidity`, since `contract.interface` is undefined.

<img width="949" alt="screen shot 2016-12-03 at 2 58 02 pm" src="https://cloud.githubusercontent.com/assets/997681/20861889/a251f970-b969-11e6-96bb-1f8c5a0c1963.png">

**Comment by luclu** [comment]
@cdetrio please make sure you checked out at a recent commit / head of `develop/master` branch for Mist as well as meteor-wallet-dapp.

**Comment by cdetrio** [comment]
Only affects meteor-dapp-wallet running standalone. closing.
