### ISSUE TITLE
Sending gives error 'invalid argument 0: empty hex string'

### ISSUE THREAD

**Issue by luclu** [ethereum/meteor-dapp-wallet#334]
```
Ethereum Wallet: 0.8.8
Geth: 1.5.6
OS: macOS 10.12.2
```

This even happens with accounts sufficiently vetted with Ether.

<img width="584" alt="bildschirmfoto 2017-01-12 um 15 22 44" 
src="https://cloud.githubusercontent.com/assets/10135872/21893358/106cce5e-d8db-11e6-968d-ef22a329140d.png">

<img width="860" alt="bildschirmfoto 2017-01-13 um 01 30 27" src="https://cloud.githubusercontent.com/assets/10135872/21913922/1b7419e2-d930-11e6-9c16-36a3f2daa391.png">

**Comment by fjl** [comment]
I tried to fix this in go-ethereum but it didn't work. The issue is that passing "" as eth_call data doesn't work with geth 1.5.6. You need to pass null or "0x".

**Comment by fjl** [comment]
This should now be resolved on the geth master branch. Please test.

**Comment by milyInzhoop** [comment]
A temporary fix is to introduce manually in each transaction the extra data 0x20 (white space).
Tested, it works: the warning message is not displayed and the transaction is completed with success.

**Comment by luclu** [comment]
@fjl geth master works again.

**Comment by milyInzhoop** [comment]
@luclu Mist 0.8.8 version launches automatically the 1.5.5 Geth version.
When it was updated with 1.5.7 one?
I need to update something manually to use the new Geth.exe?

**Comment by luclu** [comment]
@milyInzhoop I'm sorry for the inconvenience, but the geth 1.5.7 update is on hold as there might be another issue https://github.com/ethereum/mist/pull/1595#issuecomment-273197150.
However the geth-team plans to release a bug-fix release tomorrow if everything works out.

**Comment by luclu** [comment]
Fixed.
