### ISSUE TITLE
Account selection on send page

### ISSUE THREAD

**Issue by rfikki** [ethereum/meteor-dapp-wallet#36]
In the send panel there is a lot of unused space to the right.: Can you provide a scroll box with the list of accounts so that it makes it easy for "copy and paste" purposes transferring funds between owned accounts.

**Comment by alexvandesande** [comment]
Long term, we are planning on having an actual address book that should help with that. Short term we could provide simply a dropdown with your own accounts or others that you sent recently. The space still could be user for other things.

**Comment by klmoney** [comment]
When I want to send between owned accounts, I first select the receiving account, then select Deposit Ether allowing me to then select the sending account from the From drop-down list.
