### ISSUE TITLE
About dialog should be in "Help" menu.

### ISSUE THREAD

**Issue by larspensjo** [ethereum/meteor-dapp-wallet#37]

**Comment by frozeman** [comment]
Its on mac by default in the app menu. What os do you have?

**Comment by larspensjo** [comment]
Windows. E.g.

[image: Capture.PNG]


lör 26 sep. 2015 kl 12:35 skrev Fabian Vogelsteller <
notifications@github.com>:

**Comment by frozeman** [comment]
Hm. currently the about window is only mac OS X native. we can think of adding one for all platforms, but i see this a low prio.

**Comment by larspensjo** [comment]
Agreed, it is low priority.

mån 28 sep. 2015 kl 10:18 skrev Fabian Vogelsteller <
notifications@github.com>:

**Comment by alexvandesande** [comment]
we've built the about window
