### ISSUE TITLE
Account Sorting

### ISSUE THREAD

**Issue by rfikki** [ethereum/meteor-dapp-wallet#38]
There is a issue with the way accounts are sorted when having multiple accounts (>10). After the wallets are updated from sending and receiving ether. Notice accounts 10, 17 and 18 in this image:
![wallet3](https://cloud.githubusercontent.com/assets/1055929/10014427/206a745e-60e7-11e5-8c8d-ee8d02355a0e.PNG)

**Comment by alexvandesande** [comment]
We were debating account sorting just yesterday. How would you expect them to be sorted: alphabetically, by balance or by date?

**Comment by rfikki** [comment]
You could at the top provide the option for the user to sort alphabetically, date, balance, etc. 

I am not clear on what the current sorting is?

**Comment by rfikki** [comment]
I cannot remember if there is a means for the user to rename the account. But, if that is not currently available it would be useful for the user to provide that option as well.

**Comment by alexvandesande** [comment]
I was just making a quick poll on current expectations. Currently our accounts are ordered by lazy alphabetical (where 12 comes before 2). Yes, you can change the names, but it's not very obvious now.

**Comment by rfikki** [comment]
Look forward to the upgrades. Keep up the great work.

**Comment by frozeman** [comment]
Fixed in a2ac4ad
