### ISSUE TITLE
Log shows zero tokens transfer

### ISSUE THREAD

**Issue by evertonfraga** [ethereum/meteor-dapp-wallet#397]
User reported that a 19 REP token transfer resulted in log showing as 0.0

Main account (Etherbase) → 0x54Cba84f29F32...1f4D53D5951e5D5438B
an hour ago -0.000000000000000000 REP ------

**Comment by CodeJynx** [comment]
19 REP.. I think you may be confusing this transaction with the 13.3 GNO tokens that were burned by my Mist wallet.

**Comment by evertonfraga** [comment]
ok, fixed.

**Comment by stvenyin** [comment]
knowleage.
