### ISSUE TITLE
multisig api impl

### ISSUE THREAD

**Issue by romanman** [ethereum/meteor-dapp-wallet#40]
Hey @frozeman , 

Where is the implementation of the 
mulitsig contract , the api you using here 
https://github.com/ethereum/dapp-bin/blob/master/wallet/wallet.sol
?

**Comment by frozeman** [comment]
I use this one: https://github.com/ethereum/meteor-dapp-wallet/blob/master/wallet.sol
Should be almost identical, besides the `msg.sender` is `tx,origin`, as we use this contract as a code base. Its deployed here: `0x273930d21e01ee25e4c219b63259d214872220a2 `

**Comment by romanman** [comment]
got it thanks

**Comment by romanman** [comment]
got it thanks
