### ISSUE TITLE
Direct deposit to contract based wallet

### ISSUE THREAD

**Issue by gabesbit** [ethereum/meteor-dapp-wallet#41]
Hey guys. Have a problem.
I withdraw funds from exchange directly to ethereum gui wallet created contract based wallet address.
Tx shows up in blockchain with "canceled" status. What happens? Exchange will get it back? Or is my funds lost forever?

**Comment by frozeman** [comment]
Can you give the transaction hash?

**Comment by gabesbit** [comment]
Later I found out it was an OutOfGasException. Exchange has a limit of 21000 for simple value transfer only. They do not expect anyone to withdraw to contract based wallets yet. I should have been more careful too and try a small amounts first. I ignored the warnings in wallet, because it feels so "ready" and I didn't expect this kind of fault. AFAIK no other cryptocoin has similar "dangerous" behavior that can lead to loss of funds. http://frontier.ether.camp/transaction/24b34463368a1534fc79de23bba8c9c1c1320b216c3524fc5389433e3637bf63
I was lucky enough that exchange returned all funds to my account and they are working on a solution to prevent this from happening again.

**Comment by frozeman** [comment]
This is not the fault of the wallet and your funds are not lost.
In ethereum everything cost gas, so if the exchanges don't provide enough then yes it will fail. But it will basically just never move your funds..

**Comment by gabesbit** [comment]
Thanks for your answer. No one else was able to confirm this before. (Exchange credited me back but I got no answer regarding loss, so I suspected they covered the loss from their pocket :) Yeah! Now I see the funds didn't move. I also tested it out and now I am sure everything is OK.

**Comment by frozeman** [comment]
The exchange did need to cover funds, as it never left their wallets..
