### ISSUE TITLE
Does Ethereum Wallet (geth) need to write 800 GB of data to sync finally?

### ISSUE THREAD

**Issue by plasticbomb1986** [ethereum/meteor-dapp-wallet#414]
I opened it 2 weeks ago to create an address, and then i did closed it, now i did opened it again to receive some eth, it happened in the night about 1oclock, since it is still syncing and since than geth have wrote 400GB on the c drive (an SSD with 25GB free space) and it doin it by 25-145MB/s speed.
Does it neccessery to write 800GB data or there is some kind of a problem with it on my Win10PC?

During this geth is only receiving a few kb/sec from network.

**Comment by plasticbomb1986** [comment]
At the end it needed about 18 our and 1.4 TB writing to de c drive where is the appdata. For 60GB data.

**Comment by evertonfraga** [comment]
Please refer to go-ethereum repository: https://github.com/ethereum/go-ethereum/issues
