### ISSUE TITLE
Wallet payment decrease balance without actual sending of the money.

### ISSUE THREAD

**Issue by seriv** [ethereum/meteor-dapp-wallet#44]
I've just created simple contract-based wallet "test", put there 0.04 eth. It worked.
Then I've tested moving 0.02 eth from one contract-based wallet to another one. It worked, but it's not visible by blockchain explorers. After that I've tried to send 0.01 eth to external address, and I saw "invocation of the script" which decreased balance, but I do not see anything related to external address to where this 0.01 eth should go. 
Addresses here are: 
1. Creator, etherbase: 0xd2143a6dffdd21f3aaa748119262959be1a1d3c7
2. New simple contract-based wallet: 0x65eb93c4e0854e3b00a64cd18c176a7fd54dc50f
3. Another simple contract-based wallet: 0x8056338e73fde306bb5d9aedec7f4a7b8637c9e7
4. External address to which nothing was sent, although balance was 0x4dd795496f3f438fddd57d43bc81a0d0a88ee265
It looks like here the GUI of the wallet was developed, but the script for script-based contracts was not tested even for very basic functionality.

**Comment by frozeman** [comment]
Look here: http://etherscan.io/address/0x65eb93c4e0854e3b00a64cd18c176a7fd54dc50f
This is you contract and you can see that it moved money. Look for the texts " Invocation Result: Balance change from 20 Finney to 10 Finney"

If you look at the transaction here: http://etherscan.io/tx/0x0656bf3cbc7143bd5b293904bb993ba5a13424fdc6a6aa8fa72d727adfbe9478

You see in the code part that it wants to send money to the right address:
```
0xb61d27f6000000000000000000000000**4dd795496f3f438fddd57d43bc81a0d0a88ee265**000000000000000000000000000000000000000000000000002386f26fc10000000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
```

Note that this above transaction is an contract code execution, so it doesn't send ether by itself, but rather tells the contract to do so.

And the there arrived, as you can see here: http://etherscan.io/address/0x4dd795496f3f438fddd57d43bc81a0d0a88ee265

**Comment by seriv** [comment]
Thanks! I did not see transaction at the recipient side and was confused, sorry.

**Comment by frozeman** [comment]
No problem, its quite a new concept and different from bitcoin and other blockchains. Thanks for asking and the thorough description.
