### ISSUE TITLE
Accounts not displayed

### ISSUE THREAD

**Issue by Quiark** [ethereum/meteor-dapp-wallet#46]
I had geth already running. Opened the wallet app on OSX 10.10 and it displays no account. OK, I click ADD ACCOUNT, it asks for password and confirm password, then "generating account" ... and nothing. The GUI is not updated but my `geth` instance in fact has a new account. Even after restarting the wallet, nothing there.

Developer tools console:
```
Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///sockjs/info?cb=g8xfuqrd4z Failed to load resource: net::ERR_FILE_NOT_FOUND
/Users/roman/ether/Ethereum-Wallet-darwin-x64-0-3-1/Ethereum-Wallet.app/Contents/Resources/app.asar…:276 Uncaught TypeError: Cannot read property 'startingBlock' of undefined
```

**Comment by frozeman** [comment]
i might be  problem that you geth version you're running is a bit out dated..

**Comment by frozeman** [comment]
do you run the latest?

**Comment by Quiark** [comment]
It was old apparently. That would also explain why the GUI was unable to
launch geth when it was not running.

After upgrading I found my chaindata was corrupt, I shot it down with rm
-rf and now redownloading ....

čt 15. 10. 2015 v 17:02 odesílatel Fabian Vogelsteller <
notifications@github.com> napsal:
