### ISSUE TITLE
Confusion: Contract based simple wallets

### ISSUE THREAD

**Issue by larspensjo** [ethereum/meteor-dapp-wallet#47]
From a novice user perspective, there are two things that look almost the same. You can create an account, and you can create a simple "contract based wallet". These two alternatives look the same, and it can be difficult to understand the difference.

I don't understand it fully myself, but I think one "Account" can be used to control more than one "wallet", which means only one password is needed.

So what is really the recommended behavior for a novice user? Just create one account, and then use it to store ether. Or is the recommended thing to not store ether on the account, but always create at least one wallet?

So what this issue is about isn't necessarily a functionality change, but information shown to the user.

**Comment by frozeman** [comment]
We can probably improve this, but here is the gist:
Only wallets can currently show you incoming and outgoing transactions. Plus they add the possibility to add multi signature. Meaning that they can be controlled by multiple owners (accounts).

Accounts can store ether, but are more owners and signers of contracts. These are like your passwords to say.

@alexvandesande ideally we have some simple way of explaining that on start when you don't see any accounts yet. At best with not to much text :)

**Comment by alexvandesande** [comment]
I agree this can be improved on the future but by UI, not text explanations. I'll think about it

**Comment by yagitu** [comment]
To create a wallet I need some ETH. I can buy some and send it to my Etherbase account. But accounts can't list incoming transactions ???

**Comment by frozeman** [comment]
But you see the balance changes :)

**Comment by larspensjo** [comment]
Using the UI to make it self explanatory is the best. Maybe first identify
what is the recommended way we want novices to do it, and then change the
UI to enforce it. Advanced users should be able to override the behavior.

Personally, when I get two options to do something I don't understand, I
become uncertain and afraid to continue the process. Especially when there
is money involved.

tors 15 okt 2015 19:19 yagitu <notifications@github.com> skrev:

**Comment by frozeman** [comment]
@obscuren we should definitely get transaction listings :)

**Comment by obscuren** [comment]
You know what to do https://github.com/ethereum/go-ethereum/issues/1897

**Comment by frozeman** [comment]
:+1:

**Comment by yagitu** [comment]
Any faucet to test it ?

**Comment by frozeman** [comment]
we add a text in the upcoming version underneath the wallets to make it a bit more clear
