### ISSUE TITLE
Failure to create wallet

### ISSUE THREAD

**Issue by larspensjo** [ethereum/meteor-dapp-wallet#48]
I tried to create a wallet of a "simple type", but got an error message as shown:

![image](https://cloud.githubusercontent.com/assets/2412342/10510387/f7a6b8b2-7332-11e5-9736-dcc93c07e561.png)

The message is ambiguous, as I don't know how to restart a wallet. In this case, I suppose it is the app itself. After restarting the application, I got the same message and still no wallet listed. Second time I restarted, the error message was gone, but still no wallet.

**Comment by frozeman** [comment]
Have you synced you blockchain already? Are your running on a testnet?

**Comment by FrankHold** [comment]
I had the same - I did need some ether in the account.

**Comment by frozeman** [comment]
Could you explain a bit more? 
This error, should only appear if your not the main net and didn't deploy the main-wallet code, or you're on the main net and not synced.

**Comment by larspensjo** [comment]
I have installed the application at two sites (home, and another place). I tested this at home now, and it worked as expected. They are both Windows, and both are using the default provided geth. They are both running on the main net, as I can see correct amounts on my imported accounts.

I now tried it again at the "other location", and succeeded. Not sure what the difference is. Maybe I used an account with no ether on it, I can't say for sure.

**Comment by belgacoin** [comment]
I got this error also (OSX) but it disappeared after rebooting my machine.
Now, when I click on "Account 1" or "Etherbase" the message "Accounts can't list incoming transactions and are rather unsafe, please create a wallet to store ether." appears. Should I continue, because some ETH is needed I think?

**Comment by ReidCoin** [comment]
I am getting the same error on my MacBook OSX. I have Ether in 2 of 2 accounts. 2 I created with the command line in Geth... and 2 I created with the Ethereum-Wallet App. In the Ethereum-Wallet App it will not show any accounts even though it creates them (2 of them). 
With the meteor-dapp-wallet when I "add wallet" under: CONTRACT BASED WALLETS... Follow the steps... then I get the error [above]: Your stub contract has no original wallet address set. 
![eth_command_line_wallet](https://cloud.githubusercontent.com/assets/6446459/10591285/027d6b64-767b-11e5-8694-4d8cccb0dcdd.png)
![ethereum-wallet - errora](https://cloud.githubusercontent.com/assets/6446459/10591286/029ed0f6-767b-11e5-9f70-f144780d15e7.png)

If anyone can please help...

**Comment by alexvandesande** [comment]
Seems like the problem has been that the network wasn't synced yet. Please report if the problem persists
