### ISSUE TITLE
Semi-automatic import of Wallet Contracts

### ISSUE THREAD

**Issue by evertonfraga** [ethereum/meteor-dapp-wallet#497]
This feature aims to quickly show what wallet contracts the current accounts have created.

1. download a list of contracts created by a given account using a rest service (eg: etherscan).
1. match each contract's code against a wallet contract stub.
1. show which wallet contracts the user wants to import.
1. include those wallets on the list.

as a bonus, it could also show other wallet contracts the accounts are part of, without have actually created them.

**Comment by stvenyin** [comment]
see.
