### ISSUE TITLE
Last block time incorrect

### ISSUE THREAD

**Issue by taoteh1221** [ethereum/meteor-dapp-wallet#50]
"X time since last block" notification at top of Win64 GUI Wallet does not update properly when new block is found.

**Comment by frozeman** [comment]
What you mean? Do you mean because it already has a few seconds ahead?
Thats because we take the blocks timestamp, which is created when the block gets assembled in the miner, which can be a few seconds before they are actually mined.

**Comment by taoteh1221** [comment]
Ok, I see. Sorry to bother you. I presumed it was like https://stats.ethdev.com/ .
