### ISSUE TITLE
Bad transaction history for wallet

### ISSUE THREAD

**Issue by larspensjo** [ethereum/meteor-dapp-wallet#52]
I created a simple wallet (0xf2d850b176ddf0b6c1411d68ef96d2d8b7b0b480, named "TestWallet") from account 0x86889b1cea13d370e827e099e3778b17d488b3dd, and transferred one finney to it (also from 0x86889b1cea13d370e827e099e3778b17d488b3dd). After a short while, the transaction history contained a number of transactions that are not mine.

![image](https://cloud.githubusercontent.com/assets/2412342/10525800/13363dc4-7387-11e5-8358-4fd5d3a46f8c.png)

**Comment by larspensjo** [comment]
I updated to Beta2, but still see some unrelated transactions. The first one (at the bottom) is mine.

![image](https://cloud.githubusercontent.com/assets/2412342/10526942/17166610-738e-11e5-8ffa-ab9818aaf9e8.png)

**Comment by frozeman** [comment]
Yes these won't go away.
Try running `resetWallet()` from the console, after 6s it will reload and stays blank, then just restart. 
If it doesn't return your tx, do this a few times and all should be well.

**Comment by frozeman** [comment]
Hahah and btw, the 4100ether is my transaction :P

**Comment by frozeman** [comment]
If you get something like:
```js
resetWallet()
walletConnector.js:99 tx_282f981e27
collection.js:593 Uncaught Error: object missing from query(…)
```

Just continue calling `resetWallet()`

**Comment by larspensjo** [comment]
I got rid of the bad history with ´´´resetWallet()´´´, and haven't seen any more since that. I suppose the issue can be closed, if there was a fix in the latest beta?

**Comment by frozeman** [comment]
Yes it is fixed in the beta 2. Thanks for reporting
