### ISSUE TITLE
one more transaction failed to invoke script

### ISSUE THREAD

**Issue by seriv** [ethereum/meteor-dapp-wallet#54]
Can you take a look at transaction 0x07d9dbae65f760540e6d9b99da11484e06d35c907994c6b0b1444eca5c9ff49e?
It's sending 100 finney from etherbase account  0xd2143a6dffdd21f3aaa748119262959be1a1d3c7 to  created contract-based wallet 0x8056338e73fde306bb5d9aedec7f4a7b8637c9e7
Although it lists "Contract invocation", I do not see any "Input data" and it looks like these 100 finney are lost.
On this contract-based wallet, if everything worked fine, the balance should be equal to the sum of transactions received minus the sum of transactions sent plus  the sum of rewards for the mined blocks, yes?
The sum of received transactions is (0.1+5.0028683+2.99+0.02+0.02) = 8.1328683
The sum of transactions sent is 1 + 0.02 = 1.02
The mined block reward, for block 388103 is 5, as I understand.
Total should be 8.1228683 + 5 - 1.02 = 12.1128683
Now the balance is 7.01, that is 5.1028683 ethers less.
The transaction 0x39b66c720fe5952890091ba3e05f4c85a6121ea8a21c459b66d1fb2e4521c795 from ethpool.org for 5.0028683 ethers you have already explained, thank you. But it looks like transaction 0x07d9dbae65f760540e6d9b99da11484e06d35c907994c6b0b1444eca5c9ff49e for 100 finney from my own coinbase account to contract-based wallet is also lost. Is there the setting for default gas limit for transactions for the node, or for account? Or it should be increased for each transaction? Then, I think, it should be somewhere in the documentation for this application.

  Regards,
  Sergey Ivanov.

**Comment by frozeman** [comment]
This is the same problem as your last error and this:
https://github.com/ethereum/meteor-dapp-wallet/issues/57

The ether are not lost, they just never moved, as your provided only 21k gas, which is not enough for sending funds to the wallet contract.

We need to add a `ouOfGas: true` property to tell when a tx didn't worked
