### ISSUE TITLE
import old account

### ISSUE THREAD

**Issue by yagitu** [ethereum/meteor-dapp-wallet#55]
I created my first account 2 month ago using the command line tool. Now I wanted to get access to this Etherbase account using the latest wallet version (0.3.2.) and copied the related file (named UTC--2015-08-03T1....) from the old keystore folder to the new keystore folder. The old account is shown now as another Etherbase account in the wallet GUI. But when I try to create a wallet for this account or try to send some ETH, I get the error message: password not correct, but the password is definitely correct. Any idea ?

**Comment by frozeman** [comment]
We had an upgrade of the keystone, that might be the problem. @Gustav-Simonsson could you help here?

**Comment by yagitu** [comment]
Thanks! Does it mean that an account update as described here (link) should solve the problem?
https://github.com/ethereum/go-ethereum/wiki/Managing-your-accounts
I can tra it first.

**Comment by frozeman** [comment]
Should

**Comment by yagitu** [comment]
not solved with account update. I was able to unlock the account, to update and set a new password. But cant open the updated file with the latest wallet version (0.3.2.): wrong password.

**Comment by Gustav-Simonsson** [comment]
The keystore format has not changed the last 2 months. If it was possible to unlock it with geth but not through the wallet then the problem must be somewhere in-between. @yagitu any special chars in the password that could potentially be lost between wallet and node? @frozeman how are passwords passed from wallet UI to the node?

**Comment by yagitu** [comment]
special chars in my passwords (working with geth but not with the new wallet gui):

!/:.?=*+"\%~$|/  (keepass password generator special signs)

**Comment by frozeman** [comment]
i basically only pass them to the eth.unlockAccount endpoint over IPC. I do not alter them in any way

**Comment by yagitu** [comment]
if nothing works: is it possible to send my ether from my "geth account" to my "new wallet account" via command line and what are the suitable commands in detail ?

**Comment by frozeman** [comment]
Yes, see details here: https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethsendtransaction
```js
web3.eth.sendTransaction({
 from: '0x1234...',
 to: '0x1234...',
 gas: 50000,
 value: web3.toWei(1, 'ether')
});
```

**Comment by yagitu** [comment]
Thank you for instructions, when I do as recommended I must unlock my account

Please unlock account 8c3.......
Passphrase:
Account is now unlocked for this session.
"0xc7......"
>

and what is the next step ?

**Comment by frozeman** [comment]
Awesome!
