### ISSUE TITLE
keine eth in contract wallet

### ISSUE THREAD

**Issue by mampfuel** [ethereum/meteor-dapp-wallet#56]
Können sie mir bitte behilflich sein meine 800 eth coins wieder zu bekommen?
 
wollte mir 800 eth von kraken in meine wallet senden, jedoch habe ich diese coins direkt an meine erstellte contract wallet senden wollen und
die sind leider nicht angekommen.
 
die 2te überweisung von kraken in meine acount wallet hat wunderbar geklappt.
 
was muss ich nun machen damit meine 800 eth in meiner contract wallet zu sehen sind?

**Comment by obscuren** [comment]
Please file issues in English.

**Comment by frozeman** [comment]
Vermutlich gibt kraken nicht genug gas für die Transaktion. D.h. die eth sind noch in dem Kraken account. bitte wende dich an den Kraken support.

Und bitte issues in english ;)
