### ISSUE TITLE
no eth in contract wallet

### ISSUE THREAD

**Issue by mampfuel** [ethereum/meteor-dapp-wallet#57]
hi
i have send 800eth from kraken to may ethereum wallet, but my balance is zero.

I have send my eth from kraken directly to my ethereum contract wallet, but there is zero balance?

https://etherchain.org/tx/0x58d19b2000fc7997cd285deddc815e4bdbc1124971ff86e7605dec99ee8d9e97

it looks alright, but where are my coins?
i have not send the eth to my account wallet, i have send theme directly to my contract wallet, my coins are lost now?

**Comment by frozeman** [comment]
The issue is that darken doesn't supply enouyght gas, so the transaction gets mined, but never moves the money..

The money is still in krakens account, please let them know that they should at least provide 50 000 gas for transactions to be safe.

**Comment by obscuren** [comment]
Note: **your ethers are not lost**

**Comment by frozeman** [comment]
@obscuren and @gavofyork  it would be good for such transactions to have a note in the transaction receipt, which states that it was reversed.

maybe add a property like `reversed: true`. Otherwise it will be hard for kraken and also the wallet to know if a tx failed...

**Comment by obscuren** [comment]
Again, I suggest we add a `oog` field to receipts

**Comment by frozeman** [comment]
whats `oog`?

**Comment by obscuren** [comment]
**O**ut **O**f **G**as

**Comment by trapp** [comment]
Hi, I'm working for Kraken. @frozeman, in case we would allow up to 50k gas, how would we verify that a mined transaction actually moved the balance? With 21k gas it's obvious that any transaction to a contract will fail but when we up that to 50k and someone withdraws to a contract that requires more than 50k gas we won't be able to detect that.

We need to set a limit somewhere.

Adding a field to the receipt indicating this would be helpful.

**Comment by frozeman** [comment]
yes we need that field... But to be safe 100k would be enough for no, i assume.

**Comment by mampfuel** [comment]
thanks all here for the help, my problem is solved i think ;-)

**Comment by frozeman** [comment]
ours not :) There were some others who had these issues form other exchanges as well. we need to add a property telling if a tx was not fully executed.

**Comment by alexvandesande** [comment]
We have implemented a naive "out of gas" detection on the wallet. Will enhance it when we have the `out of gas` on the receipt.
