### ISSUE TITLE
No way to unlock account

### ISSUE THREAD

**Issue by joshuad31** [ethereum/meteor-dapp-wallet#58]
I consider myself to be pretty good with passwords.  I have issues unlocking accounts with the 64bit windows version of the wallet.  I could somehow unlock it once to fund a contract that allowed me to create a wallet.  Once I did that I could never transfer any funds to the wallet I created because I would constantly get "wrong password" when attempting to send from the account.

So I created lots of accounts out of frustration and now I want to go and delete accounts once i see if I can unlock them.  I can't click anywhere that will allow me to test to see if I can unlock account.  No way to delete accounts... frustrating.

**Comment by frozeman** [comment]
Go to `C:\users\app data\roaming\Ethereum\keystore` or so. There are you accounts created. You can delete them, but make sure not to delete the ones with money ;)

Are you for sure using the same password all the time? No caps lock?

**Comment by Conurtrol** [comment]
I have a similar issue. My password works on some accounts but not the two with the most ether in them. I looked in the keystore and the files for those two accounts, when viewed with notepad, are encrypted or something. The other accounts are all clearly readable. How would those two files in particular be different all of a sudden? I moved ether between them before with no problem. More importantly, is my ether recoverable? Thanks

**Comment by frozeman** [comment]
@Gustav-Simonsson any idea?

**Comment by Gustav-Simonsson** [comment]
Please try if the accounts can be unlocked using the geth command line. If there is a difference in behaviour between geth command line and the wallet we may be able to figure out more.

**Comment by Conurtrol** [comment]
Thank you for the replies. Unfortunately, I don't know how to use the geth command line. I would be willing to pay for some help with this.

**Comment by Conurtrol** [comment]
Trying to figure this out. Are the command line and the console the same thing?

**Comment by Conurtrol** [comment]
I was able to unlock some accounts in the console but not the important ones. Am I screwed? There are over 2000 ether in these accounts. Very worried

**Comment by Conurtrol** [comment]
This is from the console:
could not unlock signer account
    at InvalidResponse (<anonymous>:-81662:-155)
    at send (<anonymous>:-156322:-155)
    at sendTransaction (<anonymous>:-133322:-155)
    at <anonymous>:1:1


Any help would be greatly appreciated.

**Comment by Conurtrol** [comment]
Here is a sample of what is in the bad keyfile: ‘ÐúkF€A   W™,À ð‘ (“(+[÷¿æèï!{K¹Ýna˜V‹Òˆ’ÌíÀêe
µ4Ø¾lV    ø‘ ÎQ;¼W/^´+


Anything you can tell me about what this is would be helpful. Maybe I can find a way to fix it.

**Comment by Gustav-Simonsson** [comment]
@Conurtrol From which date is the keyfile you have troubles with?  It's possible it could be an older version which current wallet / geth is no longer compatible with. If so we can help you by providing an older version of geth to allow exporting the key into the new format.

**Comment by Gustav-Simonsson** [comment]
@Conurtrol Also, how was that keyfile created? with the presale tool, geth, eth (cpp) or some other tool?

**Comment by Conurtrol** [comment]
The date was 10/15 and it was created with the previous version of the mist wallet.

**Comment by Conurtrol** [comment]
I don't think I tried to use that wallet since i updated from previous version. Do you think it might work on previous version?

**Comment by Gustav-Simonsson** [comment]
@Conurtrol 15th October 2015?  It could work on a previous version, but I need to know the date to know which version of the keystore was used. Could you please join https://gitter.im/ethereum/go-ethereum and ping me there? Then I can also take a look at the key file.

**Comment by Conurtrol** [comment]
Ok, will do right now.

**Comment by alexvandesande** [comment]
Seems the problem is solved. Please update the wallet and report again if the problem persists.
