### ISSUE TITLE
Zero value when executing a contract that transfers ether

### ISSUE THREAD

**Issue by paulmorriss** [ethereum/meteor-dapp-wallet#59]
When I transfer ether from my wallet to an address the Execute Contract dialog 0.00 Ether above the arrow at the top. As I'm transferring I'd expect to see the amount I'm transferring there.

(This is v0.3.2 running on WIndows 7 64 bit)

**Comment by frozeman** [comment]
The tx you sending is instructing the contract to send money, so the Mist confirmation window can't  know  what you trying to do on the contract.

We will add natspec here to solve this problem.

See also https://github.com/ethereum/meteor-dapp-wallet/issues/62
