### ISSUE TITLE
Window containing electron becomes "unresponsive" while importing blocks

### ISSUE THREAD

**Issue by czepluch** [ethereum/meteor-dapp-wallet#60]
Linux 64 bit.

The block counter works fine and I see progress, but I cannot resize or move the window around. Might be a problem with my window manager, but I have never experienced this before. 

Edit: It is possible to resize the window, but it seems that the terminal that I launched the wallet from it totally frozen and unresponsive. Don't know if it is due to electron, but I have never seen this before.

**Comment by czepluch** [comment]
It is like the window running electron defies all rules set by my window manager. This is quite annoying.

**Comment by frozeman** [comment]
The splash screen is not supposed to be resizable, but it should be moveable.
Can you try this version, if it makes things better?
https://www.dropbox.com/sh/8mu15dkxlj8phu4/AACfurTFTyAg0k22g39Vgj1ka?dl=0
