### ISSUE TITLE
Array Indices

### ISSUE THREAD

**Issue by terekjudi** [ethereum/meteor-dapp-wallet#61]
I have a question regarding array indexing in Solidity. I understood that array indices start at 0 and if that's the case, the following code in the wallet contract says:

```javascript
if (pending.yetNeeded == 0) {
            // reset count of confirmations needed.
            pending.yetNeeded = m_required;
            // reset which owners have confirmed (none) - set our bitmap to 0.
            pending.ownersDone = 0;
            pending.index = m_pendingIndex.length++;
            m_pendingIndex[pending.index] = _operation;
        }
```

If the m_pendingIndex array is empty and we encounter this code on the first operation to be comfirmed, pending.index would be set to 1 since the length of m_pendingIndex.length would be zero and we would be inserting the first element in the m_pendingIndex at index value 1, and in my head that first element should be inserted at index 0. Is there something I am missing?

Thanks,

**Comment by frozeman** [comment]
@chriseth any comment?

**Comment by terekjudi** [comment]
I figured out the reason. When using an index to map the location of elements in an array, no element is placed in index 0. The reason being that when looking up the mapping for a non-existent item it returns 0 which is used to signal that the element does not exist.
