### ISSUE TITLE
Javascript error occured in the main process when quitting the wallet DApp

### ISSUE THREAD

**Issue by czepluch** [ethereum/meteor-dapp-wallet#64]
When I quit the wallet DApp I get this error message:
http://ipfs.pics/QmRzZ4GU1wvM1Nb9XmE1HQnGNR5rcYnNbyBNb9doRJKKDC

**Comment by frozeman** [comment]
When did this happened? When closing the splash screen or the wallet?

**Comment by czepluch** [comment]
When in the wallet DApp and choosing Ethereum Wallet -> Quit Ethereum from the top menubar.
