### ISSUE TITLE
revoked multisig transaction reported as executed

### ISSUE THREAD

**Issue by m888m** [ethereum/meteor-dapp-wallet#65]
When you start a multi-sig transfer 
* with the first signing account unlocked, and 
* the second one not unlocked, and 
* you revoke the transaction because of the locked status of second account, 
the transaction still gets reported on the dashboard

**Comment by frozeman** [comment]
Its a little unclear of what you did. Normally you unlock when clicking revoke/confirm.

1. So you send a multisig tx
2. You got the confirmation need?
3. you pressed revoke from the initiator account
4. the confirmation goes ways, but the tx shows as gone through? but balance didn't change right?

**Comment by m888m** [comment]
Correct.
balance did not change obviously (because transaction was revoked), but the transaction gets reported as done in dashboard

**Comment by m888m** [comment]
To clarify further: account that needs to sign as 2nd was locked. So during 2nd signing process, I got notifcation of account being locked. Then I pressed  revoke to unwind transaction

**Comment by frozeman** [comment]
Hm,

revoke basically currently means nobody agreed to the transactions, they will still be there as "confirmation needed", but hidden and therefore shouldn't show up as passed.
It seems like a race condition here. i will have a look
