### ISSUE TITLE
Wallet failing to sync to network

### ISSUE THREAD

**Issue by mkstle** [ethereum/meteor-dapp-wallet#70]
I am getting an error that is saying that there's no ethereum binary to be found, start one manually.

**Comment by mkstle** [comment]
I can get it to run when I run the wallet in administrator mode, but it freezes right away at block # 444,390.

**Comment by frozeman** [comment]
So it syncs, but then doesn't continue?
Thats an issue we already fixed in the new coming version. If you're impatient, use this one: https://www.dropbox.com/sh/8mu15dkxlj8phu4/AACfurTFTyAg0k22g39Vgj1ka?dl=0
