### ISSUE TITLE
wallet creating how long does it take?

### ISSUE THREAD

**Issue by advancetom** [ethereum/meteor-dapp-wallet#73]
I wanna create a single wallet on win7 64bit 
put in all data and since an 1h he is still creating?
Is this right?

**Comment by frozeman** [comment]
hm no. something went wrong
Do you have ether in your account, which created the wallet?

**Comment by advancetom** [comment]
No i thought i have to generate a wallet first to send Ether there

**Comment by advancetom** [comment]
Is this now an Issue or should i send Ether to my Etherbase called account?
Im confused now? :(

**Comment by frozeman** [comment]
The wallet is a contract. All contracts cost gas to create them. Yes you need to send ether to your ether base first. You can also use an accounts for storing ether, but you won't be able to see incoming transactions, just balance changes

**Comment by advancetom** [comment]
Hmm Okay ich bedanke mich mal in Deutsch für die Aufklärung :+1:

**Comment by advancetom** [comment]
new wallet creating worked now with Ether on account!!!
But the other is still creating how can i disable this?

**Comment by frozeman** [comment]
It should timeout after 50 blocks. Or when you restart the wallet.

Bitte bitte :)

**Comment by advancetom** [comment]
0x253a78891f84310e78969b4751b4bcc1a11db63b

falls das angebot noch steht mit den Mistcoins.... hehe
