### ISSUE TITLE
How to - import pre-sale wallet?

### ISSUE THREAD

**Issue by usukan** [ethereum/meteor-dapp-wallet#75]
Do you just put the wallet file given at pre-sale into the Ethereum "Keystore" folder?

Using Wallet version 0.3.5

Thanks

**Comment by frozeman** [comment]
For now you would need to import it using the command line.

Install `geth` and run `geth wallet path/to/walletfile,json`

**Comment by usukan** [comment]
OK thanks for the reply - and glad I asked.  I will just wait until the mainstream GUI wallet has a straightforward method to do this.  Please consider adding this feature asap.  Cheers

**Comment by alexvandesande** [comment]
the latest version implements this feature
