### ISSUE TITLE
bug: web3 is used before defined (firefox)

### ISSUE THREAD

**Issue by m888m** [ethereum/meteor-dapp-wallet#76]
bug: web3 is used before defined (browser:firefox) -- branch execute-contract

(appStart.js)

**Comment by m888m** [comment]
Kontext: 

* http://localhost:3000/packages/kadira_flow-router.js?268f8b1c26479d926b9ee14ca4a727315fe2da6a is being assigned a //# sourceMappingURL, but already has one kadira_flow-router.js:2484:4
* unreachable code after return statement 3stack_bignumber.js:11841:4
* http://localhost:3000/packages/3stack_bignumber.js?33286f008efec9d66ffdb3c2cef9d166dce62b45 is being assigned a //# sourceMappingURL, but already has one 3stack_bignumber.js:20433:4
* http://localhost:3000/packages/ethereum_web3.js?1050422a4f7fdef4b82193adf5f46fefb254d01a is being assigned a //# sourceMappingURL, but already has one ethereum_web3.js:15841:4
* ReferenceError: web3 is not defined walletABI.js:8:1
* ReferenceError: web3 is not defined

**Comment by m888m** [comment]
Concerns branches:
* execute-contract
* develop

Does not concern:
* master

**Comment by frozeman** [comment]
Navigating to http://ethereum-dapp-wallet.meteor.com/ which is the latest execute-contract branch, i have no problems on firefox or chrome.

Are you sure you're running it correctly?

<img width="1200" alt="screen shot 2015-11-19 at 10 35 09" src="https://cloud.githubusercontent.com/assets/232662/11267043/401fc868-8ea9-11e5-806f-36930aa50ba5.png">

**Comment by m888m** [comment]
Based on the weblink you provided, I found out that I was not using the newest version of execute-contract. (I was using the one that had the token tab instead of the contract tab). 
I have cloned the newest version, and now it works.
Thanks a lot for the heads-up :)  :+1:
