### ISSUE TITLE
bug: wallet.sol should be renamed Wallet.sol

### ISSUE THREAD

**Issue by m888m** [ethereum/meteor-dapp-wallet#77]
truffle won't compile the contract otherwise

**Comment by alexvandesande** [comment]
Can you provide a better description of the problem?

**Comment by m888m** [comment]
I'm using truffle to compile and test contracts.
The wallet contract does not compile when written with minor w. Once it is renamed with a major W (wallet.sol --> Wallet.sol), compilation works. 

Must be a consistency thing, as in the code, wallet is written with a major W

... contract Wallet is multisig, multiowned, daylimit {......

**Comment by frozeman** [comment]
In develop its uppercase now. I changed it a while ago, but githubg doesn't seem to care about capatilizarion
