### ISSUE TITLE
Send 26 ethers from my contract wallet to kraken address but...

### ISSUE THREAD

**Issue by chrisgitman** [ethereum/meteor-dapp-wallet#80]
Hi there,
I have send 26 ethers from my contract wallet to kraken address 
0xe7cef8a29176b59f46e9a85254b4256cfbf351eb
but the ethers never appeared on kraken web interface like the transaction was never made.
Then I show in this block explorer 
https://etherscan.io/address/0xe7cef8a29176b59f46e9a85254b4256cfbf351eb
that the ethers arrived to this address but without any recorded transaction!
Did I lost these ethers now?

**Comment by alexvandesande** [comment]
I've checked on the console and it looks like 
`web3.fromWei(web3.eth.getBalance('0xe7cef8a29176b59f46e9a85254b4256cfbf351eb'), "ether").toString()` returns 0. [Etherchain also doesn't show anything](https://etherchain.org/account/0xe7cef8a29176b59f46e9a85254b4256cfbf351eb)

Seems that etherscan is in the wrong here.. Is that your address or Kraken's address? Was your wallet subtracted of 26 ethers?

**Comment by chrisgitman** [comment]
Hi Alex,
thanks for answering.

Yes the wallet subtracted 26 ethers normaly.
My contract wallet address is 
0x159cfa31d239abe3f856ccf4999f98b81fe863bd
the kraken address is
0xe7cef8a29176b59f46e9a85254b4256cfbf351eb

I have sent you a screenshot from the transaction wallet to your email 
alex.vandesande@ethdev.com
This transaction has 5547 confirmations at the moment.

Tell me if you need anything else to investigate this further.

**Comment by alexvandesande** [comment]
Mmm I've asked some more senior developers. There seems two problems here: 

1) etherscan.io is displaying a different balance than ether chain and my local geth node.

2) If etherscan is correct then you sent correctly the ether to '0xe7cef8a29176b59f46e9a85254b4256cfbf351eb'. This is a private address not a contract and only the owner of that address can move it now, you should ask kraken to check if it's theirs. Is it possible that you've sent to the wrong address?

**Comment by alexvandesande** [comment]
PS. The lack of transaction logs on normal addresses is not a problem per se

**Comment by frozeman** [comment]
This is the transaction seeing the money from your wallet to kraken:
https://etherscan.io/tx/0x0f2e8ae567f0a9fa82a783757b09cd7b3cc363f4eb98ba577f1fc21e22fd9be8

It shows that you successfully send the ether and you payed enough gas. The ether are sitting now here:
https://etherscan.io/address/0xe7cef8a29176b59f46e9a85254b4256cfbf351eb

If this was a kraken generated address, then they should be able to track it properly and show your balance.
Maybe you mistyped the address?

**Comment by chrisgitman** [comment]
Hi frozeman,

thanks for answering.
No I typed correctly. 
Here is a screenshot from the wallet transaction and from the kraken address.

![kraken_address](https://cloud.githubusercontent.com/assets/2289808/11446833/9637dc16-9545-11e5-8f4f-f14360aefb67.png)
![transaction_problem_](https://cloud.githubusercontent.com/assets/2289808/11446837/9aa6cad2-9545-11e5-85a9-691280952cb8.png)

**Comment by trapp** [comment]
In your screenshot there is this warning on the Kraken deposit page:

> Attention! Send only normal transactions with an amount larger than 10 GWei / Shannon. Contracts crediting your deposit address without a proper transaction won't result in a valid deposit.

Your wallet isn't sending plain transactions with a value, it's triggering a contract that credits the funds which isn't supported by Kraken at the moment. Kraken needs to setup a deposit contract to get proper logs on events like that.

Your funds are not lost. Contact Krakens support, they will be able to return or credit the funds when the address it theirs.

**Comment by frozeman** [comment]
The money is on the kraken address, i just checked with my node, so kraken can only resolve this
```
> eth.getBalance('0xe7cef8a29176b59f46e9a85254b4256cfbf351eb')
26000000000000000000
```

**Comment by frozeman** [comment]
Yes as @trapp says, the problem is that using the wallet contract it doesn't create a "transaction" wich they can log, but instead a message call from the contract to the address, moving the value.

Kraken should either setup a deposit contract, or simply watch the balance of the created addresses..

**Comment by chrisgitman** [comment]
Hi there,

I have contacted kraken support and provided them with this issue url so they can plan for a feature upgrade to their software platform to support wallet contract message calls if they wish.
They have seen the balance on their address and they agreed to deposit the ether on one of my personal ethereum addresses. 

Thanks to all participants of this issue for their help.

Best Regards,
Chris

**Comment by sepigit** [comment]
Chris,
I the problem solved at last?
Is Kraken can credit transactions initiated from a Contract wallet?

I have same problem now with Cex.io!

**Comment by RickidyRaw** [comment]
Was this problem solved? If anyone else has this issue comment at the link below, we hope to collect enough people to be able to collectively solve this incompatibility issue, specially because the wording on the notice says use correct address not standard and that can be misleading for noobs such as myself.

https://www.reddit.com/r/icocrypto/comments/7u46rs/have_you_accidentally_used_a_kraken_address_to/?st=JJ64ULRB&sh=42675e3f

**Comment by trapp** [comment]
@RickidyRaw this issue is about sending ETH via contracts to Kraken which Kraken supports for a while now. It has nothing to do with what you're linking to (sending random ico tokens to Krakens ETH address).

**Comment by RickidyRaw** [comment]
@trapp Thanks, still new to this but learning
