### ISSUE TITLE
 transaction failed

### ISSUE THREAD

**Issue by Eisenkopf89** [ethereum/meteor-dapp-wallet#82]
Hello,
i made two days ago this transaction:

http://etherscan.io/tx/0xc5e763d3b1bbc8daa0e48beaeb5abbc2e0fa303d4bdaa54890124e67f5937b8b

124.84128972 ETHER for an exchange but they never get the Ether. Is there a way to get them back? here is also the block information i get from the transaction:

http://etherscan.io/block/0xc15c81732768924b12c49f25b2b558052f8cc9eb68daeb15971df8d7722ab83c

It would be nice if there is any way to get my Ether back on my wallet.

Thanks for your help!

With best regards
Eisenkopf89

**Comment by alexvandesande** [comment]
Which exchange was that? I believe Poloniex (or is it Kraken) has an issue where their software doesn't automatically see transactions made by contracts.

But your ether was sent to them, get in contact with their tech support, they should be able to see it.

**Comment by Eisenkopf89** [comment]
He,
it is shapeshift where i excange the ether. But tus time they didn't get any Coins from me. I wrote to the support but they told me to talk to the developers to check them.

**Comment by alexvandesande** [comment]
Your ether was sent to this address:
http://etherscan.io/address/0x4c377aed8d87831212351598647b8caeab8f390c

Do you know whose address is that? Do you have access to it? Does shape shift?

**Comment by Eisenkopf89** [comment]
This is from the shapeshift support:

The deposit address we provided to you (as you can see on the status link you have provided to us) is 0x4c377aed8d87831212351598647b8caeab8f390c. When you look that up on the ether explorer, it shows error in account as seen in this link, as I provided in my last message: https://etherchain.org/account/0x4c377aed8d87831212351598647b8caeab8f390c
This means this address never received funds. If it showed funds, we would know that our system had some issue and that we had received funds and we could assist further if that were the case. Due to the fact that no funds have posted to that address, there is nothing we can do on our side.
This is a broadcast issue with your wallet. We can see, since you provided those screen shots, that you sent money. But your wallet did not properly broadcast the funds to our deposit address, as seen in the link I posted above.
As the ether team member you have spoken with says that funds were sent, you can prove them them that this did not occur with the link I provided above, as it shows that there is error and does not show funds. They should be able to help assist you to find and retrieve these funds.
Please let me know if you have any questions about this.

Is there any way to know ans see what happend with my ether??? If you need screenshots i can give it to you!


So the adress is from Shapeshift but they just say it is not their fault as you can see^^

**Comment by alexvandesande** [comment]
I've checked your account on my own geth node and it shows the balance there. I'll going to contact the team to see if someone can figure out why ether chain and shape shift are seeing different things..
![screen shot 2015-12-10 at 4 16 04 pm](https://cloud.githubusercontent.com/assets/112898/11724145/723d6402-9f59-11e5-9e96-545e2af6bd21.png)

**Comment by obscuren** [comment]
**WARNING** many assumptions ahead.

@Eisenkopf89 i'm going to assume you've send ether to another account using the **wallet contract**. It's possible that ether chain doesn't index transaction that do the following: `accountA` -> `contract (wallet)` -> `accountB` meaning that it, internally with ether chain, didn't create the account in their local software data (**not** geth).

This is not a bug in the wallet, this is a bug in ether chain.

**Comment by obscuren** [comment]
@Eisenkopf89 do you perhaps have a transaction hash?

**Comment by obscuren** [comment]
Another thing, don't 100% rely on ether chain, etherscan and the nodes alone. Make sure you cross check and take the node (geth) as leading, definitely not blockchain explorers.

**Comment by Eisenkopf89** [comment]
@ alexvandesande
Thanks for your help! I hope they can finde the problem why shapeshift see something different on their blockcain.


@ obscuren

The Mainwallet Address is a different one then the one i send it out. The thing is, i send a few on cryptsy from my main wallet, and everything worked fine after a few minutes they get the ether.

**Comment by Eisenkopf89** [comment]
Are there any new information what was the problem?

**Comment by atonra7** [comment]
Same problem. Are there any changes?

**Comment by Eisenkopf89** [comment]
This sucks very much =/ You invest in ethereum and then it is all away =(

**Comment by atonra7** [comment]
:-(

**Comment by atonra7** [comment]
Developers? Where are you all gone? Are there any solutions?

**Comment by Eisenkopf89** [comment]
I hope they work on it for the future that the problem never happen again to other people =/

**Comment by frozeman** [comment]
Sorry for the late response, but i was on holidays, and other probably too.

The problem here is the following.

Shape shift only works when you send funds from an account, not a contract, because they watch the incoming transactions, and if they see none, they think nothing happened.

Ethereum though is working differently, because you can have message calls, which can transfer value. These are not visible on blockchain explorers, as they can't track those. Every contract which sends funds, won't create a TX, but makes a message call.

Ideally shape shift creates contracts which notify them with events, if something arrives, but their system only works with simple TX. They could have seen that they got the money, as the balance of the account changed.

Its mainly a misunderstanding of ethereum by many exchanges here and a wrong, or not safe integration. (E.g. they should put a note, to not send from contracts, etc.)

As you can see here: there is not tx with 124ether, but the balance was at one point that high, and they withdrew that money as well..
http://etherscan.io/address/0x4c377aed8d87831212351598647b8caeab8f390c
`No Of Transactions:	2 txs (124.830105507870441224 Ether)`

This is the tx where they withdrew you money: http://etherscan.io/tx/0x6e146680ab3c4a7611f18f45704514dd2e5cad5021e4475b44449044c9dea866

So they definitely got it and processed it, but their system couldn't detect it.

**Comment by frozeman** [comment]
Please contact shape shift, and let them, know, you can also lead them here i can try to explain a bit more. But mainly: they got the money and they should pay you out, its visible in the block explorers, just not as TX

**Comment by atonra7** [comment]
?????

**Comment by atonra7** [comment]
Also funds are not enrolled. They say - prove that they received something in the wallet. (https://metaexchange.info)
http://etherscan.io/tx/0xa4c99870a10389e9ff4b5e8efabdc64ee3a42d70f083d0204462af8dd078c7cd

**Comment by frozeman** [comment]
The best is you don't send from the wallet, but send the funds first to an account and then to an exchange.
Again: its the exchanges who implement ethereum wrong, if they generate accounts for incoming funds, they simply need to monitor the balances, as they won't find a transaction in the blocks..

**Comment by trapp** [comment]
> if they generate accounts for incoming funds, they simply need to monitor the balances

Monitoring balances and crediting funds based on an increase of the total balance is a very unreliable way of handling deposits. It leaves no audit trail. It's impossible to reconcile deposits in case there is a large re-org that invalidates some deposits.

There is no way for exchanges to track contract deposits properly unless they create a contract for it.

Ethereum could provide proper tools for it though. When the official network client (geth) would expose 'internal transactions' via RPC that would solve this issue. Right now, the only way to handle it is to deploy un-audited third-party libraries like bitcoinj (etherchain did this recently to display contract transaction).

**Comment by frozeman** [comment]
I agree partly, the main problem is if we store message calls (the internal transactions) then the blockchain would grow a lot faster.
Its definitely related to https://github.com/ethereum/go-ethereum/issues/1897
@obscuren @vbuterin is there anything we can do to make this easier for transactions?

**Comment by trapp** [comment]
With ethereum/go-ethereum#2156 exchanges will be able to detect internal transactions by replaying the transaction and look for successful 'CALL' logs. Of course this isn't the most efficient way to do it but it's good enough in my opinion. So, hopefully with geth 1.4.0 this issue will begin to disappear.

**Comment by vogelito** [comment]
Hi @trapp - which one is the preferred way for exchanges to see transactions made by contracts?

I work at [Bitso](https://bitso.com), the largest Bitcoin/Ether exchange in LatAm and would like to add this functionality to our exchange.

Thanks and best,
Daniel

**Comment by alexvandesande** [comment]
Hi @vogelito 

It depends on the exchange. If you have some sort of control on how your ether arrives, you can make a contract and subscribe to it so you'll be notified of deposits. In the other hand if you must have an account for each deposit, then our recommendation is that you simply loop through the accounts to check deposits.

**Comment by vogelito** [comment]
Hi @alexvandesande 

Thanks for the comment. We currently have an account for each deposit and looping around deposit addresses checking for balances would be trivial to implement. However, as @trapp rightfully mentioned, it is vital for exchanges to create an audit trail and be able to pin-point exactly what triggered a balance change, which your suggestion wouldn't do.

I'm very curious about the contract approach though. Is there a sample contract you could point me to where this is implemented?

**Comment by trapp** [comment]
Hi @vogelito 

In my view these are the options to track deposits:
1. Create a proxy contract for each customer that doesn't do much except throwing an event when Ether arrive. You can track this event using the transaction receipt in geth or parity. This catches all sorts of deposits but comes with contract creation costs per customer (~$0.04 USD atm).

Bonus: You can extend the contract to automatically forward incoming Ether to your cold storage. The depositing user will pay this transaction with the gas of his deposit.

2. Have individual accounts as deposit addresses for each user and iterate through them every couple minutes and look for balance changes. As you have mentioned, this is a nightmare for proper accounting and prone to race conditions in case of a re-org etc.

One trick to make it slightly better is to immediately send a new transaction to your cold storage once you detect a balance increase. This transaction will have a txid you can track properlt. The downside is that each deposit will issue a second transaction which also introduces additional costs which either you as exchange will have to eat or pass on to your user and credit an amount slightly smaller than what they sent. (Polo does this method if I recall correctly).

Options I wouldn't recommend:
* Using only one contract for all deposits as @alexvandesande mentioned. Users always will just send you ether, no matter how good you describe that they need to do it in a special way. With only one contract you will have to sort out lots of anonymous deposits.
* Using geth's `debug_traceTransaction` to look for CALLs to your deposit addresses in all transactions. It would work in theory and I've actually written code to process the result of `debug_traceTransaction` to handle it this way. It would leave a perfect audit trail, however, some transactions are so large that they either crash geth or web3 which is a show stopper for this.

**Comment by vogelito** [comment]
Hi @trapp - thanks so much for the thoughtful response.

I'm very curious about exploring option A). Is there by any chance sample code available anywhere to do what you describe?

Many thanks!

**Comment by trapp** [comment]
@vogelito see https://gist.github.com/trapp/d0811c2d27cf699c27e33dfe2da79795

**Comment by 257projects** [comment]
I am new to to Ethereum.  On 28 october I installed the wallet and started to make an account. I transferred 9 ETH (I changed BTC with shapeshift). My 0,15 BTC are gone from my account, but no ETH.
the wallet kept verifying and in the end no account was made (and no ETH in my account)
Can anyone help me? The info about the transfer of my BTC to BTC (of shapeshift, I think): 15yVQxr9gggx9ZkmtYaHnJ6TMnhkaMdqa3 
Please help!

**Comment by luclu** [comment]
@257projects please don't necrobump and hijack this issue. 
1. Follow these instructions: https://github.com/ethereum/mist/issues/687
2. If you still need help open a new issue [here](https://github.com/ethereum/mist/issues/new) and copy your posts content over

**Comment by erodena** [comment]
Do you have the Solution for the Problem, now? I have the same Problem. Can someone help?
If you speak German please write in German.

Greetings

**Comment by sulabh2020** [comment]
Hello Everyone here,

I am also trapped into same problem today. I brought tokens through ETH exchanges and now thy have been assigned to their wallet address. Exchange is ready for all possible help to me to get returned all the allocated tokens to me but they need a method or step by step procedure of how to call the contract "Transfer" method so they can manually transfer the coins.

Can anyone of you please help me and share the procedure of calling "Transfer" function of ICO.

Thanks in advance for all your time.

**Comment by vxn2** [comment]
Hello ppl i am stuck also why is etherscan so like frustrating

**Comment by 0marcel0** [comment]
I made a stupid mistake, I have sent ETH to Huobi and Bithumb directly from my Bitstamp account and after 6 days the money still does not appear in my accounts

Bithumb give me no ETA
Huobi told me that they need about one month. What....!!!

Someone who encountered the same problem and solved the problem till now?

**Comment by p069128** [comment]
I am having same issue with ETH from Bitstamp to Bithumb.  It’s been 3 weeks.  I did receive a recent message from Thumb support that it may not be recoverable!!  Ouch.  41.6 ETH done in Dec 2017.  Does anyone know a simple solution?  Can Thumb return deposit to sender?

**Comment by p069128** [comment]
Is it really tedious for Bithumb or any exchange that’s does not read smart contracts to manually post?  Surely some day all the exchanges will be able to read internal smart contracts on ETH.  Will the problem solve itself if Bithumb and the others update.  If you deal with ETH you are going to have to eventually accept internal/smart contracts.

Will all the exchanges be updated someday like Bitstamp and all of our money reappear?

**Comment by 0marcel0** [comment]
@p069128 You're scaring me. I've sent lots of ETHs to bithumb and huobi

**Comment by parker1836** [comment]
hello! I sent ETH from one address to another both being ETH address and it was a "success" but it does not show up in the address I sent it to. its been almost 24 hours. please help

**Comment by 0marcel0** [comment]
Yesterday, huobi.com moved my money but still has not credited my account. Interestingly, Huobi moved them before the crash. We've lost a lot of money and it's not over yet. Thanks Huobi and Thanks Bithumb

**Comment by tayoxmd** [comment]
Hello

I opened ticket to support in 24.04.2018, and no one answer to me 

i dont know what i can to do
help me please
I can't find my transaction
i sent ETH from site Bitstamp .net 

I have long kept this address And did not know that you do not accept contracts.
first I wrote a website Bitstamp.net to know about my transaction.
They said that you need to write you because it's contracts, and I just find out what contracts are.
please, put them on my account on Yobit
- 1.67985918  ETH
-TxHash  0x55b52b3571ba907beb1ecf318e4e9ba594285228c0c109c9ead42c6e88d4bbc3
- Block Explorer https://etherscan.io/tx/0x55b52b3571ba907beb1ecf318e4e9ba594285228c0c109c9ead42c6e88d4bbc3 

If I had other money with me, when i will not  aske for this money
