### ISSUE TITLE
error solc: expected primary expression  (when compiling token example)

### ISSUE THREAD

**Issue by m888m** [ethereum/meteor-dapp-wallet#83]
When I try to deploy the token example given by alex on his blog, I get:

   Error: solc: exit status 1 <stdin>:66:45: Parser error: Expected primary expression. if  (balanceOf[msg.sender] < _value) throw; ^ 

The same code compiles fine in chriseth's online compiler.

What is wrong with my config? Or is it a bug?

Note: I'm running geth on a private testnet.
![error wallet](https://cloud.githubusercontent.com/assets/13195389/11679261/96d9d9e0-9e4f-11e5-900c-edb33ac7f44c.png)

**Comment by m888m** [comment]
The compiled version works, however....

![compiled wallet is working](https://cloud.githubusercontent.com/assets/13195389/11679678/300fd7a6-9e53-11e5-9599-d6c47b12ca44.png)

**Comment by alexvandesande** [comment]
I don't understand, what has changed from both screenshots? Seems the problem was solve right?

**Comment by m888m** [comment]
Actually, the second screen shot illustrated that with the binary version, 
the contracts do compile, whereas the meteor app (Screenshot 1) does give 
an error when trying to compile the contract.

**Comment by m888m** [comment]
So the meteor version of the wallet doesn't like 'throw'
Not sure, is it possible that it would use an old version of solc?
My system is up to date... 
I'm a bit confused here, please help

**Comment by frozeman** [comment]
Its likely that the sole version in the wallet is outdated.
We will update this in the next release

**Comment by m888m** [comment]
Fabian: do you have an estimate when that would be? We are working on a project that includes the wallet, and rely on being able to use the newest version of solidity when writing contracts (would silly to "downgrade" our code just to make it compatible ;)  )
Thanks for your efforts!

**Comment by frozeman** [comment]
The next wallet release will have an updated version

**Comment by mleafer** [comment]
I am still running into this problem, and I have the latest Mist/Wallet release (0.8.4)

**Comment by naturalbrnchillr** [comment]
im having the problem now dec 12 2018
