### ISSUE TITLE
Member 'push' not found

### ISSUE THREAD

**Issue by m888m** [ethereum/meteor-dapp-wallet#86]
When I try to deploy the ballot contract from the solidity tutorial, I get the error:
>Error: :39:13: Error: Member "push" not found or not visible after argument-dependent lookup in struct Proposal storage ref[] storage ref proposals.push(Proposal({ ^------------^

I don't yet understand fully how the wallet is compiling code. Which solidity compiler is it using? 
This looks to me like it would use an old one.

![push not working](https://cloud.githubusercontent.com/assets/13195389/11723271/f0edca62-9f6d-11e5-9072-d99f37a5f7ee.png)

Please assist.

**Comment by alexvandesande** [comment]
The wallet uses the latest web3 wich includes a compiler. Are you sure solidity has push implemented? Then it's a matter of us upgrading web3.js

**Comment by m888m** [comment]
Yes I'm sure. The contract compiles fine locally.
I would highly appreciate if you could upgrade web3 soon. Thanks a lot  +1

**Comment by m888m** [comment]
Do you have an update when the updated web3 is ready?

**Comment by frozeman** [comment]
The compiler is not in web3 (which you could update yourself by including it in your app)
It's in mist. So a new mist version would be necessary. I'm currently on holidays. 
You can update the solcjs in mist yourself for the time beeing. It's in the modules folder I believe. 

Merry chistmas
Fabian

**Comment by frozeman** [comment]
The next release will have the new compiler.
