### ISSUE TITLE
contract execution function picker not picking functions

### ISSUE THREAD

**Issue by alexvandesande** [ethereum/meteor-dapp-wallet#87]
How to reproduce:

Create a contract with multiple functions. Go to the execute page, select a function and press execute. Notice the function hash. Press cancel.

Now select another function and press execute: the function hash doesn't change.

**Comment by m888m** [comment]
Had seen that too, but thought I was missing something ....   ;)  +1

**Comment by alexvandesande** [comment]
Mmm I figured out this happens specifically when you execute a transaction, then change the one you want but don't click on any of the abi inputs..

**Comment by frozeman** [comment]
Fixed in 43272ad

**Comment by frozeman** [comment]
This edge case only happened, if the function you switched to had no input parameters.
But thanks for finding. This is one of issues i explain in my blog post: http://frozeman.de/blog/2015/10/meteor-blaze-templates-done-right/
