### ISSUE TITLE
Unable to unlock signer account through the web interface

### ISSUE THREAD

**Issue by mitar** [ethereum/meteor-dapp-wallet#89]
I am running `geth` without `--unlock` because I do not want for the account to be unlocked by default. But then the wallet just complains that it could not unlock it, without any information how to do so. The best would be if the wallet would unlock it for you, ask you for the password.

**Comment by frozeman** [comment]
Hey miter, nice that your are here now too :P

The wallet can't do this, because it would need and IPC connection to gain admin rights in the node, so use the wallet desktop app, which is this app as a desktop applications.
https://github.com/ethereum/mist/releases

**Comment by mitar** [comment]
Hm, I was hopping to create a secure cloud service for Ethereum wallets.

**Comment by mitar** [comment]
BTW, [locking and unlocking is possible](https://github.com/ethereum/go-ethereum/issues/2068), but it is being removed.

**Comment by frozeman** [comment]
Its still possible, but only over IPC sockets, not over HTTP.
Miter you can connect me in skype and we can discuss you cloud service. (skype: 'frozeman.de')

**Comment by mitar** [comment]
OK.

**Comment by kaarthigaAyyappan** [comment]
> Its still possible, but only over IPC sockets, not over HTTP.
> Mitar you can connect me in skype and we can discuss you cloud service. (skype: 'frozeman.de')

I too have a problem in unlocking my ethereum account how to unlock it
