### ISSUE TITLE
Starting Ethereum node

### ISSUE THREAD

**Issue by jonesro71** [ethereum/meteor-dapp-wallet#90]
Hi, sorry if this is an obvious question, i am just trying to work through the 'how to build a crypto currency' tutorial - I have download the wallet, and when i start it i get a screen saying 'Starting Ethereum Node'  - i have left my mac on all night, but the message doesn't change? Should i be doing something else...?

**Comment by frozeman** [comment]
It seems like it couldn't start the node, try restarting. It could also be that you mac has no tmp installed
https://github.com/ethereum/mist/issues/65

This should be solved in newer geth versions.

**Comment by bulibasa** [comment]
Hello there, I am having the same issue, I tried imac, macbook pro, last beta version, all previous versions, nothing! I click on the kit, and it gets frozen on:  'Starting Ethereum Node'....that's it, I never seen anything else on my screen, is it the internet or something else? 

please help!
