### ISSUE TITLE
Amount field scrolls number

### ISSUE THREAD

**Issue by klmoney** [ethereum/meteor-dapp-wallet#92]
If the AMOUNT field is selected (insertion point inside) and you roll the mouse wheel with the cursor also on the AMOUNT field, the value will change. I know this is a lot of ifs (and possibly even a feature) but it can cause errors. On my screen, for instance, I need to scroll down to get to the SEND button after entering the amount, increasing the likelihood of this mistake.

Thanks for the great work with the app.

**Comment by alexvandesande** [comment]
Thanks klmoney!

That is a default system behaviour for numeric fields, so although I
understand how that might lead to some confusions I'm leaning towards not
trying to change it.



On Wed, Jan 13, 2016 at 3:41 AM, klmoney <notifications@github.com> wrote:

> If the AMOUNT field is selected (insertion point inside) and you roll the
> mouse wheel with the cursor also on the AMOUNT field, the value will change
> I know this is a lot of ifs (and possibly even a feature) but it can cause
> errors On my screen, for instance, I need to scroll down to get to the SEND
> button after entering the amount, increasing the likelihood of this mistake
>
> Thanks for the great work with the app
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ethereum/meteor-dapp-wallet/issues/92>.
>



-- 

Alex Van de Sande
UX Designer

**Comment by frozeman** [comment]
We could make it a textfield, but as alex said its the default for number inputs and the chrome guys put some thoughts in it.

I'm split about changing it

**Comment by klmoney** [comment]
Thanks guys. I appreciate the issue better now.

**Comment by frozeman** [comment]
I'll keep this open as a possibility, if other people complain about the same we might change it, or @alexvandesande?

**Comment by alexvandesande** [comment]
Agree. I would not change it now.

On Wed, Jan 13, 2016 at 2:39 PM, Fabian Vogelsteller <
notifications@github.com> wrote:

> I'll keep this open as a possibility, if other people complain about the
> same we might change it, or @alexvandesande
> <https://github.com/alexvandesande>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ethereum/meteor-dapp-wallet/issues/92#issuecomment-171356460>
> .
>



-- 

Alex Van de Sande
UX Designer
