### ISSUE TITLE
[Question] MULTISIGNATURE WALLET

### ISSUE THREAD

**Issue by FrankHold** [ethereum/meteor-dapp-wallet#93]
Hi, I have created a multisignature wallet without any problem. There are some Functions which I would like to understand but I do not want to try them blind because I have some ether in the account. My guess on it

removeOwner "Removes one of the owners"
isOwner "?"
resetSpentToday "Sets the amount spend to 0"
addOwner "A new additional owner"
confirm "?"
setDailyLimit "new value for the daily limit"
execute "send some ether or wei? (_value)"
revoke "?"
changeRequirement "change the number of accounts necessary to have full access"
kill "sounds dangerous - moves the total amount to (_to) and deletes the contract"
changeOwner "change the address of one owner"

Execute from "select the owner to do the action"

Thank you in advance!

**Comment by frozeman** [comment]
These are functions of you wallet contract, which are not easy to use, i would rather simply stick to using the wallet to transfer funds and don't change the owners.

**Comment by FrankHold** [comment]
ok
