### ISSUE TITLE
On OSX wallet won't start ethereum node?

### ISSUE THREAD

**Issue by powerproperty** [ethereum/meteor-dapp-wallet#96]
I dont know what Im doing wrong. I download the zip and open it ... I press the Ethereum Wallet.app and it doesnt go anywhere. It gets stuck at the "Starting Ethereum node..." and it just stays there for hours. 

I downloaded the zip again, restarted my computer, and no luck. the app gets stuck. What am I doing wrong?

I use 
  Model Name:	iMac
  Model Identifier:	iMac12,2
  Processor Name:	Intel Core i5
  Processor Speed:	2.7 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Memory:	16 GB
  Boot ROM Version:	IM121.0047.B23
  SMC Version (system):	1.72f1

**Comment by frozeman** [comment]
Please list your log files, you can find them when clicking in the menu auf Backup -> Mist data folder
the *.log files


> 
> 
>

**Comment by powerproperty** [comment]
I dont understand what youre saying... 

Im just clicking on the blue icon which says "Etherem Wallet.app" and its on my Mac desktop ...and it looks like its about to open but never goes anywhere on my Mac.  The Ethereum Wallet.app is located in my folder called Ethereum-Wallet-darwin-x64-0-3-9. The folder is on my desktop and the Etherem Wallet app is inside the folder.

**Comment by frozeman** [comment]
Look in the menu of the application (top bar), click there on Backup -> Mist data folder and give me the log files in this folder ;)

**Comment by powerproperty** [comment]
In my "Backup" Tab on the top bar, it gives two options when I click on the "Backup" Tab ...it says "Backup Accounts" and "Backup App Data" ...i dont see "Mist data" folder

**Comment by powerproperty** [comment]
Keep in mind, this is for a Mac computer, not windows

**Comment by frozeman** [comment]
ok i meant "Backup App Data"

**Comment by 44blox** [comment]
Hi!
i hav the problem that it crash when it say starting node

**Comment by frozeman** [comment]
@44blox this issue is known and already noted in other issues, its a missing dependency in your mac installation. we will fix this in a following geth version

**Comment by 44blox** [comment]
@frozeman okie dokie.
