### ISSUE TITLE
API (price) calls while the block-chain is catching up

### ISSUE THREAD

**Issue by vcealicu** [ethereum/meteor-dapp-wallet#97]
I've noticed that while geth catches up in the background, the wallet does api calls to the Pricing api. This is fine as i don't mind the extra traffic but, the issue is: as soon as the wallet displays you see a flurry of activity on the Balance (as it processes all the API responses) 

I think the pricing API calls should only be made after the blockchain is synced. 

Feel free to close this if this is intended behavior and not a bug.

The reproduce it, just close the wallet for a day (make sure you have BTC or EUR selected before you close it) and as soon as you open it after the block chain sync you'll see a lot of activity on the balance for a few seconds.

Also in the future (no urgency on this at all) i could give you access to the streamer as that would be a much better experience for the users (so i can stream all the price changes directly to you rather than poll for data changes)

**Comment by frozeman** [comment]
It should only make a lot of requests, if there is a bunch of transactions coming in, as he gets the past data for each of them

**Comment by vcealicu** [comment]
It's not that it makes a lot of requests, i think the price requests start as soon as the wallet is open, and happen while the blockchain is syncing. So when the wallet opens for the first time the price in the upper right corner moves really fast for a few seconds as it processes all the /price api calls that were made while the blockchain was syncing. 

Again, here i am not talking about the historical pricing, that is fine to happen whenever you find a transaction, this is the snapshot (what is the price now) API.

I'm not worried about the api calls, it's the UI and the fact that it just moves a lot for 2-5 seconds after the wallet finally loads.

But it's not a big deal, just thought it would not hurt to mention it.

**Comment by frozeman** [comment]
Defintely helps. I will take Look

**Comment by luclu** [comment]
Thanks @vcealicu, the behaviour has been changed since your report. Also we used an floating animation for the balance.
