### ISSUE TITLE
New Mist user - RE: Etherbase ID on initial setup

### ISSUE THREAD

**Issue by Etherism** [ethereum/meteor-dapp-wallet#98]
Hello, I'm a bit stuck after installing Mist on my Windows machine.. I initially loaded the app and seemed to not connect to any peers on initial setup. After logging out and running into some "node already running messages" I went ahead and copied the provided address on Etherbase and sent some Kraken Ether to the address thinking when the network finally sync'd the funds would arrive. Unfortunately upon the first sync with peers the Etherbase address changed, and I'm not sure how to point the wallet to the original Mist generated address the Kraken deposit was sent to.. Any assistance would be greatly appreciated.

**Comment by alexvandesande** [comment]
Had you Connected to the testnet previously? For a matter of security mist avoids using the same accounts for both but if that's the case you can still have access to your funds by getting the testnet private keys into the main net. I'll dog around to see how that works.

**Comment by Etherism** [comment]
Ok, crisis averted... Whew..

What we ended up doing was uploading the key to https://www.myetherwallet.com/ then sending the funds back over to Kraken until my nerves settle, lol.

I did raise a comment with the Mist developer on the fact that many non devs may not have a need for such an easily accessible test area that could trigger more impatient folks than me to think their funds have vanished, when in reality they are parked in a key the wallet is not pointing to..

Lesson learned, and thank you everyone for your help.
