### ISSUE TITLE
how to import presale wallet?

### ISSUE THREAD

**Issue by nekrasovvitalik** [ethereum/meteor-dapp-wallet#99]
Hello. I want to ask you can i import my presale wallet? if yes, so how to do it? Thank you in advance

**Comment by frozeman** [comment]
You currently need to do this on the command line: https://github.com/ethereum/go-ethereum/wiki/Command-Line-Options#accounts

You can find the node binary on windows/linux in `wallet/resources/node/geth`
and max OS X  `Ethereum Wallet.app/Contents/Resources/node/geth`

**Comment by nekrasovvitalik** [comment]
I'm sorry for my stupid question. I just usual user and i don't have experience in ether.
must i open geth and write this:" geth wallet import /path/to/my/etherwallet.json"?

**Comment by frozeman** [comment]
You have to open a terminal, navigate to where the binary is and then write the above. Please google how to do this.

**Comment by alexvandesande** [comment]
This feature has been implemented on the latest release
